package com.dnkdialer.companion

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * E2E P4 Part 2 (a3) — emits and pins `e2e-evidence/kdf-vectors-P4-proposal.json`.
 *
 * ## What this file is for
 *
 * E2E-SPEC §13 freezes the SAS, the padding and the dedupe parameters. It does
 * **not** freeze the key schedule, and no reference `lib/e2e/kdf.mjs` exists —
 * P0 published only `sas.mjs` and `padding.mjs`. So the Android lane is, by
 * accident of ordering, the first implementation of the KDF. Writing it and
 * saying nothing would freeze a cross-lane byte layout from one side, and the
 * failure mode is the worst one available: P2 implements the prose differently,
 * the two sides derive different keys, and the only symptom is "encrypted mode
 * never pairs".
 *
 * So the layout ships as a **proposal with vectors**, in the same shape as
 * `tests/sas-vectors.json`, and this test does two jobs:
 *
 *  1. It PINS the layout — if anyone edits [E2eKdf]'s framing, the committed
 *     vectors stop matching and the build fails, rather than the browser failing
 *     silently three phases later.
 *  2. It gives P2/P3 something to implement against: the file carries the exact
 *     info-string bytes and the exact derived keys, not just a description.
 *
 * Regenerate deliberately with `-De2e.writeVectors=true`, which is the only way
 * the committed file can change. A test that silently rewrites its own expected
 * output is not a test.
 */
class E2eKdfVectorsTest {

    private val file = File("../e2e-evidence/kdf-vectors-P4-proposal.json")

    /**
     * Fixed, human-readable inputs. The recipient keys are FIXED POINTS, not
     * freshly generated ones — a vectors file whose inputs change per run pins
     * nothing.
     */
    private fun vectors(): String {
        val ctx = E2eKdf.PairContext(
            pairingId = "pair-7f3a9c21",
            userId = "user-0191aa",
            phoneDeviceId = "dev-phone-01",
            peerDeviceId = "dev-web-01",
            pairEpoch = 42L,
        )
        // Deterministic 32-byte inputs. Not real ECDH output; the point of the
        // file is to pin the KDF, and the KDF must not care where its IKM came
        // from.
        val z = ByteArray(32) { (it * 7 + 1).toByte() }
        val sk = ByteArray(32) { (0xA0 + it).toByte() }

        val web = E2eKdf.fromHex(RECIPIENT_WEB)
        val sw = E2eKdf.fromHex(RECIPIENT_SW)
        // Proves the fixed points are real P-256 points, not typed-in noise.
        E2eKeyEncoding.validate(web)
        E2eKeyEncoding.validate(sw)

        val traffic = E2eKdf.deriveTrafficKeys(sk, ctx)

        return buildString {
            append("{\n")
            append("  \"_comment\": \"P4 PROPOSAL, not frozen. E2E-SPEC v1.0 s13 does not freeze the KDF. ")
            append("Generated by E2eKdfVectorsTest; regenerate with -De2e.writeVectors=true.\",\n")
            append("  \"version\": \"cc-e2e-v1\",\n")
            append("  \"hash\": \"HKDF-SHA-256\",\n")
            append("  \"context\": {\n")
            append("    \"pairingId\": \"${ctx.pairingId}\",\n")
            append("    \"userId\": \"${ctx.userId}\",\n")
            append("    \"phoneDeviceId\": \"${ctx.phoneDeviceId}\",\n")
            append("    \"peerDeviceId\": \"${ctx.peerDeviceId}\",\n")
            append("    \"pairEpoch\": ${ctx.pairEpoch}\n")
            append("  },\n")
            append("  \"contextBytesHex\": \"${E2eKdf.toHex(E2eKdf.pairContextBytes(ctx))}\",\n")
            append("  \"labels\": {\n")
            append("    \"kek\": \"${E2eKdf.LABEL_KEK}\",\n")
            append("    \"phoneToComputer\": \"${E2eKdf.LABEL_PHONE_TO_COMPUTER}\",\n")
            append("    \"computerToPhone\": \"${E2eKdf.LABEL_COMPUTER_TO_PHONE}\"\n")
            append("  },\n")
            append("  \"traffic\": {\n")
            append("    \"sessionKeyHex\": \"${E2eKdf.toHex(sk)}\",\n")
            append("    \"infoP2cHex\": \"${E2eKdf.toHex(E2eKdf.infoFor(E2eKdf.LABEL_PHONE_TO_COMPUTER, ctx))}\",\n")
            append("    \"infoC2pHex\": \"${E2eKdf.toHex(E2eKdf.infoFor(E2eKdf.LABEL_COMPUTER_TO_PHONE, ctx))}\",\n")
            append("    \"phoneToComputerKeyHex\": \"${E2eKdf.toHex(traffic.phoneToComputer)}\",\n")
            append("    \"computerToPhoneKeyHex\": \"${E2eKdf.toHex(traffic.computerToPhone)}\"\n")
            append("  },\n")
            append("  \"kek\": {\n")
            append("    \"sharedSecretHex\": \"${E2eKdf.toHex(z)}\",\n")
            append("    \"recipients\": [\n")
            append(recipientJson("web", web, z, ctx))
            append(",\n")
            append(recipientJson("extension-sw", sw, z, ctx))
            append("\n    ]\n")
            append("  },\n")
            append(aeadSection())
            append("}\n")
        }
    }

    /**
     * GATE1 Addendum A1's amended AEAD vectors, ADDED to the ratified file.
     *
     * A1: *"kdf-vectors-P4-proposal.json is ratified unchanged and becomes
     * tests/kdf-vectors.json. Forge MUST ADD to it, and MUST NOT regenerate the
     * existing values."* Everything above this section is produced by the same
     * code that produced the ratified file, and
     * `the committed KDF vectors match what the code derives` is what proves
     * those values did not move.
     *
     * A1 also requires the web/SW lane to assert against the same file:
     * *"or the file only constrains one of the three implementations."*
     */
    private fun aeadSection(): String {
        val frameType = "SMS_RECEIVED"
        val kid = "kid-01"
        val seq = 7L
        val dir = E2eEnvelope.Direction.PHONE_TO_COMPUTER
        val epoch = 42L
        val prefix = E2eKdf.fromHex("11223344")
        val key = E2eKdf.fromHex(A1_P2C_KEY)
        val hi = "hi".toByteArray(Charsets.UTF_8)
        val sealed = E2eEnvelope.seal(key, kid, seq, dir, epoch, prefix, frameType, hi)
        val q = "\""
        return buildString {
            append("  ${q}aead$q: {\n")
            append("    ${q}_comment$q: ${q}GATE1 Addendum A1 (AMENDED). AES-256-GCM, 128-bit tag. ")
            append("nonce = sessionPrefix(4B random per kid+direction) || be64(seq). ")
            append("AAD = 0x21 u8(len) frameType || 0x22 u8(len) kid || 0x23 be64(seq) || ")
            append("0x24 u8 direction (0x01=p2c, 0x02=c2p) || 0x25 be64(pairEpoch). ")
            append("AAD is RE-ENCODED from parsed fields, NEVER the JSON header bytes. ")
            append("Pad per s13.4 FIRST, then seal.$q,\n")
            append("    ${q}vectorA$q: {\n")
            append("      ${q}frameType$q: $q$frameType$q,\n")
            append("      ${q}kid$q: $q$kid$q,\n")
            append("      ${q}seq$q: $seq,\n")
            append("      ${q}direction$q: ${q}p2c$q,\n")
            append("      ${q}pairEpoch$q: $epoch,\n")
            append("      ${q}aadHex$q: $q${E2eKdf.toHex(E2eEnvelope.aad(frameType, kid, seq, dir, epoch))}$q,\n")
            append("      ${q}sessionPrefixHex$q: $q${E2eKdf.toHex(prefix)}$q,\n")
            append("      ${q}nonceHex$q: $q${E2eKdf.toHex(E2eEnvelope.nonceFor(prefix, seq))}$q,\n")
            append("      ${q}keyHex$q: $q${E2eKdf.toHex(key)}$q,\n")
            append("      ${q}plaintextUtf8$q: ${q}hi$q,\n")
            append("      ${q}paddedPlaintextHex$q: $q${E2eKdf.toHex(E2ePadding.pad(frameType, hi))}$q,\n")
            append("      ${q}ciphertextHex$q: $q${E2eKdf.toHex(sealed.ciphertext)}$q\n")
            append("    },\n")
            append("    ${q}vectorB_mustThrowAtEncode$q: {\n")
            append("      ${q}_comment$q: ${q}A1 item 4: u8 is ratified ONLY because the cap is enforced. ")
            append("Each case MUST throw at encode on every platform — silent truncation to ")
            append("len and 0xFF re-creates the framing collision the addendum exists to kill.$q,\n")
            append("      ${q}maxBytes$q: 255,\n")
            append("      ${q}cases$q: [${q}userId$q, ${q}phoneDeviceId$q, ${q}peerDeviceId$q, ")
            append("${q}kid$q, ${q}frameType$q]\n")
            append("    },\n")
            append("    ${q}vectorC_tamper$q: {\n")
            append("      ${q}_comment$q: ${q}Change any ONE of these AAD fields and the GCM tag check ")
            append("MUST fail. Proves the AAD is actually passed — a silently dropped AAD is ")
            append("indistinguishable from a working one on the happy path.$q,\n")
            append("      ${q}fields$q: [${q}frameType$q, ${q}kid$q, ${q}seq$q, ${q}direction$q, ")
            append("${q}pairEpoch$q]\n")
            append("    },\n")
            append("    ${q}vectorD_crossDirection$q: {\n")
            append("      ${q}_comment$q: ${q}computerToPhoneKeyHex MUST NOT open vectorA.ciphertextHex. ")
            append("This is what makes a reflection attack inert.$q,\n")
            append("      ${q}keyHex$q: $q$A1_C2P_KEY$q\n")
            append("    }\n")
            append("  }\n")
        }
    }

    private fun recipientJson(
        kind: String,
        sec1: ByteArray,
        z: ByteArray,
        ctx: E2eKdf.PairContext,
    ): String = buildString {
        append("      {\n")
        append("        \"kind\": \"$kind\",\n")
        append("        \"publicKeySec1Hex\": \"${E2eKdf.toHex(sec1)}\",\n")
        append("        \"publicKeyBase64Url\": \"${E2eKeyEncoding.toBase64Url(sec1)}\",\n")
        append("        \"kekInfoHex\": \"${E2eKdf.toHex(E2eKdf.kekInfo(ctx, sec1))}\",\n")
        append("        \"kekHex\": \"${E2eKdf.toHex(E2eKdf.deriveKek(z, ctx, sec1))}\"\n")
        append("      }")
    }

    @Test
    fun `the committed KDF vectors match what the code derives`() {
        val produced = vectors()
        if (System.getProperty("e2e.writeVectors") == "true") {
            file.parentFile?.mkdirs()
            file.writeText(produced, Charsets.UTF_8)
            println("WROTE ${file.absolutePath} (${produced.length} chars)")
            return
        }
        assertTrue(
            "missing ${file.absolutePath} — regenerate with -De2e.writeVectors=true",
            file.exists()
        )
        assertEquals(
            "the KDF framing changed but the committed vectors did not — " +
                "if this is intentional, regenerate with -De2e.writeVectors=true AND tell " +
                "the web lane, because P2/P3 must derive identical bytes",
            file.readText(Charsets.UTF_8).replace("\r\n", "\n"),
            produced
        )
    }

    @Test
    fun `the two recipients derive different KEKs in the committed vectors`() {
        val text = vectors()
        val keks = Regex("\"kekHex\": \"([0-9a-f]{64})\"").findAll(text)
            .map { it.groupValues[1] }.toList()
        assertEquals("two recipients", 2, keks.size)
        assertTrue("a wrap for the web page must not open in the SW", keks[0] != keks[1])
    }

    companion object {
        /** traffic.phoneToComputerKeyHex from the ratified file — A1 vector A. */
        private const val A1_P2C_KEY =
            "b12f964e487f7bf39a0b37df9715ca9e606c642c28bdf430f51b2051a4e0e060"

        /** traffic.computerToPhoneKeyHex from the ratified file — A1 vector D. */
        private const val A1_C2P_KEY =
            "d519d9b52f5258e36a05e4c06a55e652a250c103743acb77ffcc6d7249bfac7d"

        /**
         * Two fixed, valid P-256 public points in uncompressed SEC1 hex. The
         * first is the standard base point G (SEC 2 §2.4.2) — a value anyone can
         * verify independently. The second is a second fixed point so the
         * per-recipient KEK separation is visible in the file.
         */
        private const val RECIPIENT_WEB =
            "04" +
                "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296" +
                "4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5"

        /** [2]G on P-256. */
        private const val RECIPIENT_SW =
            "04" +
                "7cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc47669978" +
                "07775510db8ed040293d9ac69f7430dbba7dade63ce982299e04b79d227873d1"
    }
}
