#!/usr/bin/env node
/**
 * tests/kdf-vectors.test.mjs — the key schedule and the AEAD layout are frozen,
 * and stay frozen (E2E-SPEC §13.10, which GATE1's Addendum A1 calls §13.9).
 *
 * Three implementations must derive identical bytes from identical inputs: the
 * web page (P2), the extension service worker (P3) and the Android app (P4).
 * When they disagree the only symptom is "Encrypted mode never pairs", with
 * every log line on every side reporting success — and the tempting "fix" is to
 * adjust a vector until the numbers match, at which point the vectors stop
 * describing anything. tests/kdf-vectors.json is the contract that makes that
 * visible; Kotlin's E2eKdfVectorsTest asserts the SAME file.
 *
 * A fixture generated by the implementation it tests proves only that the code
 * is deterministic. So, as sas-vectors does, this file adds independent things:
 *
 *   1. An INDEPENDENT HKDF. The module derives through WebCrypto
 *      (`crypto.subtle.deriveBits`); the cross-check recomputes every key
 *      through `node:crypto.hkdfSync`, a different RFC 5869 implementation. If
 *      the frozen layout were being hashed wrongly but consistently, these two
 *      would still have to agree — and they are the two code paths the web and
 *      Android sides actually use.
 *
 *   2. The INFO BYTES, not just the keys. A 32-byte key that matches proves the
 *      whole chain, but a key that does NOT match says nothing about where the
 *      divergence is. Each vector pins its exact context and info bytes, so a
 *      mismatch is caught at the byte that differs.
 *
 *   3. NEGATIVE cases that are the whole point of ratifying u8: three 256-byte
 *      ids must THROW. A test that only proves the happy path does not prove the
 *      cap is enforced, and silent truncation to `len & 0xff` recreates exactly
 *      the collision the framing exists to kill.
 *
 *   4. A TAMPER case. A silently-ignored AAD is indistinguishable from a working
 *      one on the happy path, so the AAD is only proven by a frame that fails.
 *
 *   5. A CROSS-DIRECTION negative. k_c2p must not open a p2c frame, which is
 *      what makes a reflected frame inert.
 *
 *   6. A DRIFT GUARD. The layout is re-encoded from the constants written in the
 *      SPEC TEXT — parsed out of e2e-evidence/E2E-SPEC-v1.0.md §13.10, not
 *      imported from the module — and compared against what lib/e2e/kdf.mjs
 *      produces. This is the web/SW lane's equivalent of Android's drift
 *      assertion: an edit to the module that nobody mirrored into the spec (or
 *      the reverse) fails here instead of at a pairing.
 *
 * Plus a service-worker-context run: the same module, executed in a worker with
 * `process`, `Buffer`, `require`, `window` and `document` removed and `self`
 * bound to the global — the constraint set an MV3 service worker imposes.
 */

import { readFileSync } from 'node:fs';
import { hkdfSync } from 'node:crypto';
import { Worker } from 'node:worker_threads';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import {
  pairContext, kekInfo, trafficInfo, kek, trafficKeys, nonce, aad, seal, open, createSender,
  toHex, fromHex, DIR_P2C, DIR_C2P, SESSION_PREFIX_BYTES, SEC1_P256_BYTES, MAX_PREFIXED_BYTES,
} from '../lib/e2e/kdf.mjs';
import { padPlaintext } from '../lib/e2e/padding.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const KDF_MODULE = join(ROOT, 'lib', 'e2e', 'kdf.mjs');
const SPEC = join(ROOT, 'e2e-evidence', 'E2E-SPEC-v1.0.md');

const V = JSON.parse(readFileSync(join(HERE, 'kdf-vectors.json'), 'utf8'));
const CTX_INPUT = V.context;
const CTX = pairContext(CTX_INPUT);
const A = V.aead.vectorA;

let passed = 0;
let failed = 0;
function check(name, ok, detail = '') {
  if (ok) { passed++; return; }
  failed++;
  console.error(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
}
/** JSON.stringify throws on a BigInt, and several values here are BigInt seqs. */
function show(v) {
  return typeof v === 'bigint' ? `${v}n` : JSON.stringify(v);
}
function eq(name, actual, expected) {
  check(name, actual === expected, `expected ${show(expected)}, got ${show(actual)}`);
}
async function throws(name, fn, mustMention = null) {
  let message = null;
  try { await fn(); } catch (e) { message = String(e && e.message || e); }
  check(name, message !== null, 'it did NOT throw');
  if (message !== null && mustMention) {
    check(`${name}: the error names the cause`, message.includes(mustMention), message);
  }
}

// ── 1. the ratified schedule reproduces, context and info bytes first ───────
// These values are P4's proposal, recomputed independently by Security and
// ratified byte for byte in A1. They are NOT to be regenerated — a "fix" here
// is a protocol change, not a test repair.
eq('contextBytesHex', toHex(CTX), V.contextBytesHex);
eq('infoP2cHex', toHex(trafficInfo(CTX, DIR_P2C)), V.traffic.infoP2cHex);
eq('infoC2pHex', toHex(trafficInfo(CTX, DIR_C2P)), V.traffic.infoC2pHex);

const phoneKeys = await trafficKeys({
  pairingId: CTX_INPUT.pairingId,
  sessionKey: fromHex(V.traffic.sessionKeyHex),
  context: CTX,
  role: 'phone',
});
const computerKeys = await trafficKeys({
  pairingId: CTX_INPUT.pairingId,
  sessionKey: fromHex(V.traffic.sessionKeyHex),
  context: CTX_INPUT, // the same context, passed as inputs rather than bytes
  role: 'computer',
});

eq('k_p2c', toHex(phoneKeys.send.rawBytes), V.traffic.phoneToComputerKeyHex);
eq('k_c2p', toHex(phoneKeys.recv.rawBytes), V.traffic.computerToPhoneKeyHex);
eq('pairContext(inputs) === pairContext(bytes): computer derives the same k_p2c',
  toHex(computerKeys.recv.rawBytes), V.traffic.phoneToComputerKeyHex);
eq('the computer SENDS on k_c2p', toHex(computerKeys.send.rawBytes), V.traffic.computerToPhoneKeyHex);
eq('the phone sends p2c', phoneKeys.send.direction, DIR_P2C);
eq('the computer sends c2p', computerKeys.send.direction, DIR_C2P);
check('k_p2c !== k_c2p', V.traffic.phoneToComputerKeyHex !== V.traffic.computerToPhoneKeyHex);

for (const r of V.kek.recipients) {
  eq(`${r.kind}: kekInfoHex`, toHex(kekInfo(CTX, r.publicKeySec1Hex)), r.kekInfoHex);
  const k = await kek({
    pairingId: CTX_INPUT.pairingId,
    sharedSecret: fromHex(V.kek.sharedSecretHex),
    context: CTX,
    recipientKey: r.publicKeySec1Hex,
  });
  eq(`${r.kind}: kekHex`, toHex(k), r.kekHex);
  const point = fromHex(r.publicKeySec1Hex);
  eq(`${r.kind}: K_i is ${SEC1_P256_BYTES} bytes`, point.length, SEC1_P256_BYTES);
  eq(`${r.kind}: K_i is 0x04-prefixed (uncompressed SEC1)`, point[0], 0x04);
}

// The KEK binds K_i: that is what stops a wrap minted for the web page from
// opening in the service worker. Two recipients, same shared secret, different
// KEKs — an implementation that dropped K_i from the info would pass every
// happy-path assertion above and fail this one.
check('the two recipients get DIFFERENT KEKs from the SAME shared secret',
  V.kek.recipients[0].kekHex !== V.kek.recipients[1].kekHex);

// ── 2. independent HKDF over the frozen info bytes ──────────────────────────
// node:crypto.hkdfSync is a different RFC 5869 implementation from
// crypto.subtle.deriveBits. Agreement between them is the real cross-check.
const salt = Buffer.from(CTX_INPUT.pairingId, 'utf8');
function independentHkdf(ikmHex, infoHex) {
  return Buffer.from(hkdfSync('sha256', Buffer.from(ikmHex, 'hex'), salt, Buffer.from(infoHex, 'hex'), 32))
    .toString('hex');
}
eq('k_p2c (node:crypto, independent)',
  independentHkdf(V.traffic.sessionKeyHex, V.traffic.infoP2cHex), V.traffic.phoneToComputerKeyHex);
eq('k_c2p (node:crypto, independent)',
  independentHkdf(V.traffic.sessionKeyHex, V.traffic.infoC2pHex), V.traffic.computerToPhoneKeyHex);
for (const r of V.kek.recipients) {
  eq(`${r.kind}: kek (node:crypto, independent)`,
    independentHkdf(V.kek.sharedSecretHex, r.kekInfoHex), r.kekHex);
}

// ── 3. vector A: the full AEAD frame ───────────────────────────────────────
const sender = { ...phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex) };
const aadA = aad({
  frameType: A.frameType, kid: A.kid, seq: A.seq, direction: sender.direction, pairEpoch: A.pairEpoch,
});

eq('A: keyHex is the vector file\'s own k_p2c', A.keyHex, V.traffic.phoneToComputerKeyHex);
eq('A: aadHex', toHex(aadA), A.aadHex);
eq('A: nonceHex', toHex(nonce(sender.sessionPrefix, A.seq)), A.nonceHex);
eq('A: the §13.4 padded plaintext (pad FIRST, then seal)',
  toHex(padPlaintext(A.frameType, new TextEncoder().encode(A.plaintextUtf8))), A.paddedPlaintextHex);

const ctA = await seal({
  sender, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch,
  plaintext: new TextEncoder().encode(A.plaintextUtf8),
});
eq('A: ciphertextHex', toHex(ctA), A.ciphertextHex);
eq('A: 80 bytes = 64 ciphertext || 16 tag', ctA.length, A.ciphertextBytes);

// …and it opens, back to the original plaintext, on the receiving side's own
// receive key. The computer RECEIVES on k_p2c, which is what phoneKeys.send is.
const receiver = { ...computerKeys.recv, sessionPrefix: fromHex(A.sessionPrefixHex) };
eq('A: the computer receives on k_p2c', toHex(receiver.rawBytes), V.traffic.phoneToComputerKeyHex);
const openedA = await open({
  receiver, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch, ciphertext: ctA,
});
eq('A: round-trips to the original plaintext', new TextDecoder().decode(openedA), A.plaintextUtf8);

// ── 4. (B) the u8 cap is ENFORCED, not assumed ─────────────────────────────
// A1 ratified u8 over u16 on the condition that the cap throws. Truncation to
// `len & 0xff` would recreate the ("ab","cd") vs ("a","bcd") collision in the
// one code path nobody tests.
const OVERSIZE = V.aead.negativeOversizeIds.fillByte.repeat(V.aead.negativeOversizeIds.lengthBytes);
eq('B: the oversize fixture is 256 bytes', new TextEncoder().encode(OVERSIZE).length, MAX_PREFIXED_BYTES + 1);

await throws('B1: a 256-byte userId throws at encode',
  () => pairContext({ ...CTX_INPUT, userId: OVERSIZE }), 'userId');
await throws('B2: a 256-byte peerDeviceId throws at encode',
  () => pairContext({ ...CTX_INPUT, peerDeviceId: OVERSIZE }), 'peerDeviceId');
await throws('B3: a 256-byte kid throws at encode',
  () => aad({ frameType: A.frameType, kid: OVERSIZE, seq: A.seq, direction: DIR_P2C, pairEpoch: A.pairEpoch }),
  'kid');
// The cap is a CAP, not a ban: 255 bytes is still legal, or the assertions above
// would also pass on an implementation that rejected every long id.
check('B control: a 255-byte userId is ACCEPTED (the cap is off-by-one-proof)',
  pairContext({ ...CTX_INPUT, userId: 'a'.repeat(MAX_PREFIXED_BYTES) }).length > MAX_PREFIXED_BYTES);
await throws('B4: a 256-byte phoneDeviceId throws at encode',
  () => pairContext({ ...CTX_INPUT, phoneDeviceId: OVERSIZE }), 'phoneDeviceId');
await throws('B5: a 256-byte frameType throws at encode',
  () => aad({ frameType: OVERSIZE, kid: A.kid, seq: A.seq, direction: DIR_P2C, pairEpoch: A.pairEpoch }),
  'frameType');

// ── 5. (C) the AAD is actually passed — proven by a frame that FAILS ────────
// Flipping the direction byte 0x01 -> 0x02 is a relay replaying a p2c frame as
// c2p. A silently-ignored AAD is indistinguishable from a working one on the
// happy path, so only the failure proves it.
const T = V.aead.tamper;
const tamperedAad = fromHex(A.aadHex);
eq('C: the byte under test is the direction byte', tamperedAad[T.byteIndex], T.originalByte);
tamperedAad[T.byteIndex] = T.tamperedByte;
eq('C: tamperedAadHex', toHex(tamperedAad), T.tamperedAadHex);
check('C: exactly one byte differs',
  fromHex(A.aadHex).reduce((n, b, i) => n + (b === tamperedAad[i] ? 0 : 1), 0) === 1);

{
  const subtle = globalThis.crypto.subtle;
  const key = await subtle.importKey('raw', fromHex(A.keyHex), { name: 'AES-GCM' }, false, ['decrypt']);
  const params = { name: 'AES-GCM', iv: fromHex(A.nonceHex), tagLength: 128 };
  await throws('C: the tag check FAILS under the tampered AAD',
    () => subtle.decrypt({ ...params, additionalData: tamperedAad }, key, ctA));
  // Control: the SAME call with the untampered AAD must succeed, or the
  // assertion above would pass on a decrypt that was broken for another reason.
  const good = new Uint8Array(await subtle.decrypt({ ...params, additionalData: fromHex(A.aadHex) }, key, ctA));
  eq('C control: the UNtampered AAD opens the same frame', toHex(good), A.paddedPlaintextHex);
}

// A tampered seq, kid or frameType must fail the same way — the AAD binds all
// five fields, not just the one the vector happens to flip.
for (const [name, patch] of [
  ['seq (moved to slip the §13.5 dedupe window)', { seq: A.seq + 1 }],
  ['kid (relabelled key id)', { kid: 'kid-02' }],
  ['frameType (CALL_STATUS relabelled as SMS_RECEIVED)', { frameType: 'CALL_STATUS' }],
  ['pairEpoch (replayed into another epoch)', { pairEpoch: A.pairEpoch + 1 }],
]) {
  const bad = { ...receiver };
  await throws(`C: a tampered ${name} fails the tag`, () => open({
    receiver: bad,
    frameType: patch.frameType ?? A.frameType,
    kid: patch.kid ?? A.kid,
    seq: patch.seq ?? A.seq,
    pairEpoch: patch.pairEpoch ?? A.pairEpoch,
    ciphertext: ctA,
  }));
}

// ── 6. (D) directional keys never cross ────────────────────────────────────
// k_c2p must not open a p2c frame. This is what makes a reflected frame inert:
// a frame bounced back at its sender cannot decrypt under the sender's own key.
eq('D: the vector names k_c2p', V.aead.crossDirection.keyHex, V.traffic.computerToPhoneKeyHex);
{
  // Deliberately mis-wired: the c2p key bytes with the p2c direction in the AAD,
  // which is the strongest form of the test — the AAD is RIGHT and only the key
  // is wrong, so nothing but the key can be what fails.
  const wrong = {
    direction: DIR_P2C,
    rawBytes: fromHex(V.aead.crossDirection.keyHex),
    sessionPrefix: fromHex(A.sessionPrefixHex),
  };
  await throws('D: k_c2p does NOT open vector A', () => open({
    receiver: wrong, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch, ciphertext: ctA,
  }));
  check('D: the vector declares it must not open', V.aead.crossDirection.mustOpen === false);
}

// There is no keyForDirection() to call with the wrong argument (A1 (2)): a
// caller gets .send and .recv and cannot name the other side's pair.
{
  const exported = await import('../lib/e2e/kdf.mjs');
  check('no keyForDirection-style helper is exported',
    !Object.keys(exported).some((k) => /^(keyFor|getKey|keyOf)/i.test(k)),
    Object.keys(exported).join(','));
  await throws('trafficKeys refuses an unknown role',
    () => trafficKeys({ pairingId: 'p', sessionKey: new Uint8Array(32).fill(1), context: CTX, role: 'relay' }),
    'role');
}

// ── 7. persist-before-emit / FAIL CLOSED (A1 (3)) ──────────────────────────
// The rule A1 calls the single most likely one to be quietly skipped, so it is
// a constructor precondition rather than a comment — and therefore testable.
{
  const committed = [];
  const s = createSender({
    trafficKey: phoneKeys.send,
    sessionPrefix: fromHex(A.sessionPrefixHex),
    resumeFrom: 0,
    commitSeq: async (next) => { committed.push(next); },
  });
  const first = await s.nextSeq();
  const second = await s.nextSeq();
  eq('the counter starts at the proven floor', first, 0n);
  eq('the counter strictly increments', second, 1n);
  check('the NEXT value was durably committed before the seq was handed out',
    committed.length === 2 && committed[0] === 1n && committed[1] === 2n, committed.join(','));

  await throws('FAIL CLOSED: no proven counter floor -> refuse to encrypt',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex), commitSeq: async () => {},
    }), 'rekey');
  await throws('FAIL CLOSED: no durable commit -> refuse to encrypt',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex), resumeFrom: 0,
    }), 'commitSeq');
  await throws('a sessionPrefix of the wrong width is refused',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: new Uint8Array(SESSION_PREFIX_BYTES + 1),
      resumeFrom: 0, commitSeq: async () => {},
    }), 'sessionPrefix');
  // A restored device that resumes ABOVE its floor is fine; the rule is that it
  // must PROVE the floor, not that the counter may never jump.
  const restored = createSender({
    trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex),
    resumeFrom: 9000, commitSeq: async () => {},
  });
  eq('a restored sender resumes at its proven floor, never at 0', await restored.nextSeq(), 9000n);
}

// ── 8. malformed input fails loudly rather than deriving something ─────────
await throws('a K_i that is not 65 bytes is refused at import',
  () => kekInfo(CTX, '04' + 'aa'.repeat(63)), '65');
await throws('a 65-byte K_i that is not 0x04-prefixed is refused',
  () => kekInfo(CTX, '02' + 'aa'.repeat(64)), '0x04');
await throws('an all-zero shared secret is refused',
  () => kek({ pairingId: 'p', sharedSecret: new Uint8Array(32), context: CTX, recipientKey: V.kek.recipients[0].publicKeySec1Hex }),
  'all-zero');
await throws('an empty pairingId is refused (it is the HKDF salt)',
  () => trafficKeys({ pairingId: '', sessionKey: fromHex(V.traffic.sessionKeyHex), context: CTX, role: 'phone' }),
  'pairingId');
await throws('a direction byte outside {0x01,0x02} is refused',
  () => aad({ frameType: A.frameType, kid: A.kid, seq: A.seq, direction: 0x03, pairEpoch: A.pairEpoch }),
  'direction');
await throws('a negative pairEpoch is refused',
  () => pairContext({ ...CTX_INPUT, pairEpoch: -1 }), 'uint64');
// be64 is BigInt, not a JS number: a value above 2^53 must not silently round.
check('be64 does not round above 2^53',
  toHex(pairContext({ ...CTX_INPUT, pairEpoch: 9007199254740993n })).endsWith('20000000000001'),
  toHex(pairContext({ ...CTX_INPUT, pairEpoch: 9007199254740993n })).slice(-16));

// ── 9. the framing actually disambiguates ──────────────────────────────────
// Without the tags and u8 length prefixes, ("ab","cd") and ("a","bcd") flatten
// to the same context bytes and two different pairings derive the SAME traffic
// keys. This is the bug the whole section exists for.
{
  const base = { peerDeviceId: 'x', pairEpoch: 1 };
  const one = toHex(pairContext({ ...base, userId: 'ab', phoneDeviceId: 'cd' }));
  const two = toHex(pairContext({ ...base, userId: 'a', phoneDeviceId: 'bcd' }));
  check('("ab","cd") and ("a","bcd") produce DIFFERENT context bytes', one !== two, `both are ${one}`);
}
// Tag ranges are disjoint — a SAS transcript can never be replayed as a KDF
// info string. The SAS uses 0x01..0x04; nothing here may.
{
  const tags = [0x11, 0x12, 0x13, 0x14, 0x15, 0x21, 0x22, 0x23, 0x24, 0x25];
  check('no KDF/AEAD tag falls in the SAS range 0x01..0x04', tags.every((t) => t > 0x04));
  check('the KDF and AEAD ranges do not overlap', new Set(tags).size === tags.length);
}

// ── 10. DRIFT GUARD: the spec text and the module must agree ───────────────
// The web/SW lane's equivalent of Android's E2eKdfVectorsTest drift assertion.
// The layout is re-encoded from the constants written in §13.10 of the SPEC —
// parsed out of the markdown, NOT imported from the module — so an edit to
// lib/e2e/kdf.mjs that nobody mirrored into the spec (or the reverse) fails
// here rather than at a pairing.
{
  const specText = readFileSync(SPEC, 'utf8');
  const section = specText.slice(specText.indexOf('### 13.10 Key schedule + AEAD'));
  check('§13.10 exists in the spec', section.length > 0);
  check('§13 names A1 as the amending authority', /AMENDING AUTHORITY/.test(specText));
  check('§13.10 records that A1 calls it §13.9', /A1's own text calls the new section "§13\.9"/.test(specText));

  // Pull the tag bytes out of the spec's own fenced layout blocks. The blocks
  // are located by content, not by position, and `pairEpoch` is read from EACH
  // block separately: it is tagged 0x14 in the pair context and 0x25 in the
  // AAD, and a parser that found only the first would happily "confirm" a spec
  // that had lost the AAD's epoch binding entirely.
  const blocks = section.match(/```[\s\S]*?```/g) || [];
  const ctxBlock = blocks.find((b) => b.includes('pairContext =')) || '';
  const aadBlock = blocks.find((b) => b.includes('AAD =')) || '';
  check('drift guard: §13.10 carries a pairContext block and an AAD block',
    ctxBlock.length > 0 && aadBlock.length > 0);

  const tagIn = (block, pattern) => {
    const m = block.match(new RegExp(`(0x[0-9a-f]{2}) ${pattern}`));
    return m ? m[1] : null;
  };
  const specTag = (block, label) => tagIn(block, `u8\\(len\\) ${label}\\b`);
  const specTags = {
    userId: specTag(ctxBlock, 'userId'),
    phoneDeviceId: specTag(ctxBlock, 'phoneDeviceId'),
    peerDeviceId: specTag(ctxBlock, 'peerDeviceId'),
    pairEpoch: tagIn(ctxBlock, 'be64\\(pairEpoch\\)'),
    recipientKey: tagIn(ctxBlock, 'u8\\(65\\) K_i'),
    frameType: specTag(aadBlock, 'frameType'),
    kid: specTag(aadBlock, 'kid'),
    seq: tagIn(aadBlock, 'be64\\(seq\\)'),
    direction: tagIn(aadBlock, 'u8 direction'),
    aadPairEpoch: tagIn(aadBlock, 'be64\\(pairEpoch\\)'),
  };
  eq('drift guard: the AAD epoch tag is 0x25, not the context\'s 0x14',
    specTags.aadPairEpoch !== specTags.pairEpoch, true);
  for (const [name, v] of Object.entries(specTags)) {
    check(`drift guard: §13.10 states a tag for ${name}`, /^0x[0-9a-f]{2}$/.test(String(v)), String(v));
  }

  // Re-encode pairContext from the SPEC's tags, independently of kdf.mjs.
  const te = new TextEncoder();
  const u8len = (tag, s) => {
    const b = te.encode(s);
    return [tag, b.length, ...b];
  };
  const be64n = (n) => {
    const out = [];
    let v = BigInt(n);
    for (let i = 7; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
    return out;
  };
  const specContext = Uint8Array.from([
    ...u8len(parseInt(specTags.userId, 16), CTX_INPUT.userId),
    ...u8len(parseInt(specTags.phoneDeviceId, 16), CTX_INPUT.phoneDeviceId),
    ...u8len(parseInt(specTags.peerDeviceId, 16), CTX_INPUT.peerDeviceId),
    parseInt(specTags.pairEpoch, 16), ...be64n(CTX_INPUT.pairEpoch),
  ]);
  eq('drift guard: the spec text re-encodes to the module\'s pairContext bytes',
    toHex(specContext), toHex(CTX));
  eq('drift guard: …and to the frozen vector', toHex(specContext), V.contextBytesHex);

  const specAad = Uint8Array.from([
    ...u8len(parseInt(specTags.frameType, 16), A.frameType),
    ...u8len(parseInt(specTags.kid, 16), A.kid),
    parseInt(specTags.seq, 16), ...be64n(A.seq),
    parseInt(specTags.direction, 16), A.direction,
    parseInt(specTags.aadPairEpoch, 16), ...be64n(A.pairEpoch),
  ]);
  eq('drift guard: the spec text re-encodes to the module\'s AAD bytes', toHex(specAad), toHex(aadA));

  // The reserved-range table is a freeze condition, not decoration.
  for (const range of ['`0x01..0x04`', '`0x11..0x15`', '`0x21..0x25`']) {
    check(`drift guard: §13.10.1 reserves ${range}`, section.includes(range));
  }
  check('drift guard: §13.10 keeps the labels the vectors were derived under',
    section.includes('"cc-e2e-v1/kek"') && section.includes('"cc-e2e-v1/p2c"') && section.includes('"cc-e2e-v1/c2p"'));
  // Control: the parser must be capable of failing. If the section slice were
  // empty or the regexes matched nothing, every assertion above would be
  // vacuously green on a spec that says nothing at all.
  check('drift guard control: a tag the spec does NOT state parses as null',
    specTag('somethingTheSpecNeverMentions') === null);
}

// ── 11. the module is service-worker clean, statically ─────────────────────
{
  // Comments are stripped FIRST. The module's own header explains that it must
  // not touch `window` or `document`; a grep over the raw source matches that
  // prose and fails a module that is in fact clean.
  const src = readFileSync(KDF_MODULE, 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
  check('kdf.mjs imports no Node built-in', !/from\s+['"]node:/.test(src));
  check('kdf.mjs touches no DOM global', !/\b(window|document|localStorage)\b/.test(src));
  check('kdf.mjs imports only ./padding.mjs',
    (src.match(/^import .*$/gm) || []).every((l) => l.includes('./padding.mjs')));
  check('the comment-stripper did not empty the file', /export function pairContext/.test(src));
}

// ── 12. …and dynamically: the same vectors, under SW constraints ───────────
// `process`, `Buffer` and `require` are removed and `self` is bound to the
// global before the module is imported, which is the shape an MV3 service
// worker presents. A module that reached for any of them would throw here and
// pass everywhere else — and P3 is the lane that would find out in production.
const swResult = await new Promise((resolve, reject) => {
  const bootstrap = `
    const { parentPort, workerData } = require('node:worker_threads');
    (async () => {
      try {
        const { ctx, pairingId, sessionKeyHex, A, kekHexInputs } = workerData;
        globalThis.self = globalThis;
        delete globalThis.process;
        delete globalThis.Buffer;
        delete globalThis.require;
        globalThis.window = undefined;
        globalThis.document = undefined;
        const m = await import(workerData.url);
        const context = m.fromHex(ctx);
        const keys = await m.trafficKeys({
          pairingId, sessionKey: m.fromHex(sessionKeyHex), context, role: 'phone',
        });
        const sender = { ...keys.send, sessionPrefix: m.fromHex(A.sessionPrefixHex) };
        const ct = await m.seal({
          sender, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch,
          plaintext: new TextEncoder().encode(A.plaintextUtf8),
        });
        const keksOut = [];
        for (const r of kekHexInputs) {
          keksOut.push([r.kind, m.toHex(await m.kek({
            pairingId, sharedSecret: m.fromHex(r.sharedSecretHex), context, recipientKey: r.publicKeySec1Hex,
          }))]);
        }
        let capThrew = false;
        try { m.pairContext({ userId: 'a'.repeat(256), phoneDeviceId: 'b', peerDeviceId: 'c', pairEpoch: 1 }); }
        catch { capThrew = true; }
        parentPort.postMessage({
          ok: true,
          p2c: m.toHex(keys.send.rawBytes),
          c2p: m.toHex(keys.recv.rawBytes),
          ct: m.toHex(ct),
          keks: keksOut,
          capThrew,
        });
      } catch (e) {
        parentPort.postMessage({ ok: false, error: String(e && e.message || e) });
      }
    })();
  `;
  const w = new Worker(bootstrap, {
    eval: true,
    workerData: {
      url: pathToFileURL(KDF_MODULE).href,
      ctx: V.contextBytesHex,
      pairingId: CTX_INPUT.pairingId,
      sessionKeyHex: V.traffic.sessionKeyHex,
      A,
      kekHexInputs: V.kek.recipients.map((r) => ({
        kind: r.kind, publicKeySec1Hex: r.publicKeySec1Hex, sharedSecretHex: V.kek.sharedSecretHex,
      })),
    },
  });
  w.once('message', (m) => { resolve(m); w.terminate(); });
  w.once('error', reject);
});

check('SW context: the module runs with no process/Buffer/require/DOM', swResult.ok, swResult.error);
if (swResult.ok) {
  eq('SW context: k_p2c', swResult.p2c, V.traffic.phoneToComputerKeyHex);
  eq('SW context: k_c2p', swResult.c2p, V.traffic.computerToPhoneKeyHex);
  eq('SW context: vector A ciphertext', swResult.ct, A.ciphertextHex);
  for (const [kind, hex] of swResult.keks) {
    eq(`SW context: ${kind} kek`, hex, V.kek.recipients.find((r) => r.kind === kind).kekHex);
  }
  check('SW context: the u8 cap still throws', swResult.capThrew);
}

// ── result ─────────────────────────────────────────────────────────────────
const total = passed + failed;
console.log(`kdf-vectors: ${passed}/${total} checks passed`);
process.exit(failed === 0 ? 0 : 1);
