#!/usr/bin/env node
/**
 * tests/kdf-vectors.test.mjs — the key schedule and the AEAD layout are frozen,
 * and stay frozen (E2E-SPEC §13.10, which GATE1's Addendum A1 calls §13.9).
 *
 * Three implementations must derive identical bytes from identical inputs: the
 * web page (P2), the extension service worker (P3) and the Android app (P4).
 * When they disagree the only symptom is "Encrypted mode never pairs", with
 * every log line on every side reporting success — and the tempting "fix" is to
 * adjust a vector until the numbers match, at which point the vectors stop
 * describing anything. tests/kdf-vectors.json is the contract that makes that
 * visible; Kotlin's E2eKdfVectorsTest asserts the SAME file.
 *
 * A fixture generated by the implementation it tests proves only that the code
 * is deterministic. So, as sas-vectors does, this file adds independent things:
 *
 *   1. An INDEPENDENT HKDF. The module derives through WebCrypto
 *      (`crypto.subtle.deriveBits`); the cross-check recomputes every key
 *      through `node:crypto.hkdfSync`, a different RFC 5869 implementation. If
 *      the frozen layout were being hashed wrongly but consistently, these two
 *      would still have to agree — and they are the two code paths the web and
 *      Android sides actually use.
 *
 *   2. The INFO BYTES, not just the keys. A 32-byte key that matches proves the
 *      whole chain, but a key that does NOT match says nothing about where the
 *      divergence is. Each vector pins its exact context and info bytes, so a
 *      mismatch is caught at the byte that differs.
 *
 *   3. NEGATIVE cases that are the whole point of ratifying u8: three 256-byte
 *      ids must THROW. A test that only proves the happy path does not prove the
 *      cap is enforced, and silent truncation to `len & 0xff` recreates exactly
 *      the collision the framing exists to kill.
 *
 *   4. A TAMPER case. A silently-ignored AAD is indistinguishable from a working
 *      one on the happy path, so the AAD is only proven by a frame that fails.
 *
 *   5. A CROSS-DIRECTION negative. k_c2p must not open a p2c frame, which is
 *      what makes a reflected frame inert.
 *
 *   6. A DRIFT GUARD. The layout is re-encoded from the constants written in the
 *      SPEC TEXT — parsed out of e2e-evidence/E2E-SPEC-v1.0.md §13.10, not
 *      imported from the module — and compared against what lib/e2e/kdf.mjs
 *      produces. This is the web/SW lane's equivalent of Android's drift
 *      assertion: an edit to the module that nobody mirrored into the spec (or
 *      the reverse) fails here instead of at a pairing.
 *
 * Plus a service-worker-context run: the same module, executed in a worker with
 * `process`, `Buffer`, `require`, `window` and `document` removed and `self`
 * bound to the global — the constraint set an MV3 service worker imposes.
 */

import { readFileSync } from 'node:fs';
import { hkdfSync } from 'node:crypto';
import { Worker } from 'node:worker_threads';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import {
  pairContext, kekInfo, trafficInfo, kek, trafficKeys, nonce, aad, seal, open, createSender,
  toHex, fromHex, DIR_P2C, DIR_C2P, SESSION_PREFIX_BYTES, SEC1_P256_BYTES, MAX_PREFIXED_BYTES,
  // A2 (derived nonce prefixes) and A3 (the ctx wire form).
  noncePrefixInfo, deriveNoncePrefixes, hkdfBytes, pairContextFromWire,
  LABEL_NP2C, LABEL_NC2P, PAIR_EPOCH_WIRE_RE,
  // A4 (the canonical peer of a multi-recipient pairing).
  canonicalPeerDeviceId,
} from '../lib/e2e/kdf.mjs';
import { padPlaintext } from '../lib/e2e/padding.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const KDF_MODULE = join(ROOT, 'lib', 'e2e', 'kdf.mjs');
const SPEC = join(ROOT, 'e2e-evidence', 'E2E-SPEC-v1.0.md');

const V = JSON.parse(readFileSync(join(HERE, 'kdf-vectors.json'), 'utf8'));
const CTX_INPUT = V.context;
const CTX = pairContext(CTX_INPUT);
const A = V.aead.vectorA;

let passed = 0;
let failed = 0;
function check(name, ok, detail = '') {
  if (ok) { passed++; return; }
  failed++;
  console.error(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
}
/** JSON.stringify throws on a BigInt, and several values here are BigInt seqs. */
function show(v) {
  return typeof v === 'bigint' ? `${v}n` : JSON.stringify(v);
}
function eq(name, actual, expected) {
  check(name, actual === expected, `expected ${show(expected)}, got ${show(actual)}`);
}
async function throws(name, fn, mustMention = null) {
  let message = null;
  try { await fn(); } catch (e) { message = String(e && e.message || e); }
  check(name, message !== null, 'it did NOT throw');
  if (message !== null && mustMention) {
    check(`${name}: the error names the cause`, message.includes(mustMention), message);
  }
}

// ── 1. the ratified schedule reproduces, context and info bytes first ───────
// These values are P4's proposal, recomputed independently by Security and
// ratified byte for byte in A1. They are NOT to be regenerated — a "fix" here
// is a protocol change, not a test repair.
eq('contextBytesHex', toHex(CTX), V.contextBytesHex);
eq('infoP2cHex', toHex(trafficInfo(CTX, DIR_P2C)), V.traffic.infoP2cHex);
eq('infoC2pHex', toHex(trafficInfo(CTX, DIR_C2P)), V.traffic.infoC2pHex);

const phoneKeys = await trafficKeys({
  pairingId: CTX_INPUT.pairingId,
  sessionKey: fromHex(V.traffic.sessionKeyHex),
  context: CTX,
  role: 'phone',
});
const computerKeys = await trafficKeys({
  pairingId: CTX_INPUT.pairingId,
  sessionKey: fromHex(V.traffic.sessionKeyHex),
  context: CTX_INPUT, // the same context, passed as inputs rather than bytes
  role: 'computer',
});

eq('k_p2c', toHex(phoneKeys.send.rawBytes), V.traffic.phoneToComputerKeyHex);
eq('k_c2p', toHex(phoneKeys.recv.rawBytes), V.traffic.computerToPhoneKeyHex);
eq('pairContext(inputs) === pairContext(bytes): computer derives the same k_p2c',
  toHex(computerKeys.recv.rawBytes), V.traffic.phoneToComputerKeyHex);
eq('the computer SENDS on k_c2p', toHex(computerKeys.send.rawBytes), V.traffic.computerToPhoneKeyHex);
eq('the phone sends p2c', phoneKeys.send.direction, DIR_P2C);
eq('the computer sends c2p', computerKeys.send.direction, DIR_C2P);
check('k_p2c !== k_c2p', V.traffic.phoneToComputerKeyHex !== V.traffic.computerToPhoneKeyHex);

for (const r of V.kek.recipients) {
  eq(`${r.kind}: kekInfoHex`, toHex(kekInfo(CTX, r.publicKeySec1Hex)), r.kekInfoHex);
  const k = await kek({
    pairingId: CTX_INPUT.pairingId,
    sharedSecret: fromHex(V.kek.sharedSecretHex),
    context: CTX,
    recipientKey: r.publicKeySec1Hex,
  });
  eq(`${r.kind}: kekHex`, toHex(k), r.kekHex);
  const point = fromHex(r.publicKeySec1Hex);
  eq(`${r.kind}: K_i is ${SEC1_P256_BYTES} bytes`, point.length, SEC1_P256_BYTES);
  eq(`${r.kind}: K_i is 0x04-prefixed (uncompressed SEC1)`, point[0], 0x04);
}

// The KEK binds K_i: that is what stops a wrap minted for the web page from
// opening in the service worker. Two recipients, same shared secret, different
// KEKs — an implementation that dropped K_i from the info would pass every
// happy-path assertion above and fail this one.
check('the two recipients get DIFFERENT KEKs from the SAME shared secret',
  V.kek.recipients[0].kekHex !== V.kek.recipients[1].kekHex);

// ── 2. independent HKDF over the frozen info bytes ──────────────────────────
// node:crypto.hkdfSync is a different RFC 5869 implementation from
// crypto.subtle.deriveBits. Agreement between them is the real cross-check.
const salt = Buffer.from(CTX_INPUT.pairingId, 'utf8');
function independentHkdf(ikmHex, infoHex) {
  return Buffer.from(hkdfSync('sha256', Buffer.from(ikmHex, 'hex'), salt, Buffer.from(infoHex, 'hex'), 32))
    .toString('hex');
}
eq('k_p2c (node:crypto, independent)',
  independentHkdf(V.traffic.sessionKeyHex, V.traffic.infoP2cHex), V.traffic.phoneToComputerKeyHex);
eq('k_c2p (node:crypto, independent)',
  independentHkdf(V.traffic.sessionKeyHex, V.traffic.infoC2pHex), V.traffic.computerToPhoneKeyHex);
for (const r of V.kek.recipients) {
  eq(`${r.kind}: kek (node:crypto, independent)`,
    independentHkdf(V.kek.sharedSecretHex, r.kekInfoHex), r.kekHex);
}

// ── 3. vector A: the full AEAD frame ───────────────────────────────────────
const sender = { ...phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex) };
const aadA = aad({
  frameType: A.frameType, kid: A.kid, seq: A.seq, direction: sender.direction, pairEpoch: A.pairEpoch,
});

eq('A: keyHex is the vector file\'s own k_p2c', A.keyHex, V.traffic.phoneToComputerKeyHex);
eq('A: aadHex', toHex(aadA), A.aadHex);
eq('A: nonceHex', toHex(nonce(sender.sessionPrefix, A.seq)), A.nonceHex);
eq('A: the §13.4 padded plaintext (pad FIRST, then seal)',
  toHex(padPlaintext(A.frameType, new TextEncoder().encode(A.plaintextUtf8))), A.paddedPlaintextHex);

const ctA = await seal({
  sender, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch,
  plaintext: new TextEncoder().encode(A.plaintextUtf8),
});
eq('A: ciphertextHex', toHex(ctA), A.ciphertextHex);
eq('A: 80 bytes = 64 ciphertext || 16 tag', ctA.length, A.ciphertextBytes);

// …and it opens, back to the original plaintext, on the receiving side's own
// receive key. The computer RECEIVES on k_p2c, which is what phoneKeys.send is.
const receiver = { ...computerKeys.recv, sessionPrefix: fromHex(A.sessionPrefixHex) };
eq('A: the computer receives on k_p2c', toHex(receiver.rawBytes), V.traffic.phoneToComputerKeyHex);
const openedA = await open({
  receiver, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch, ciphertext: ctA,
});
eq('A: round-trips to the original plaintext', new TextDecoder().decode(openedA), A.plaintextUtf8);

// ── 4. (B) the u8 cap is ENFORCED, not assumed ─────────────────────────────
// A1 ratified u8 over u16 on the condition that the cap throws. Truncation to
// `len & 0xff` would recreate the ("ab","cd") vs ("a","bcd") collision in the
// one code path nobody tests.
const OVERSIZE = V.aead.negativeOversizeIds.fillByte.repeat(V.aead.negativeOversizeIds.lengthBytes);
eq('B: the oversize fixture is 256 bytes', new TextEncoder().encode(OVERSIZE).length, MAX_PREFIXED_BYTES + 1);

await throws('B1: a 256-byte userId throws at encode',
  () => pairContext({ ...CTX_INPUT, userId: OVERSIZE }), 'userId');
await throws('B2: a 256-byte peerDeviceId throws at encode',
  () => pairContext({ ...CTX_INPUT, peerDeviceId: OVERSIZE }), 'peerDeviceId');
await throws('B3: a 256-byte kid throws at encode',
  () => aad({ frameType: A.frameType, kid: OVERSIZE, seq: A.seq, direction: DIR_P2C, pairEpoch: A.pairEpoch }),
  'kid');
// The cap is a CAP, not a ban: 255 bytes is still legal, or the assertions above
// would also pass on an implementation that rejected every long id.
check('B control: a 255-byte userId is ACCEPTED (the cap is off-by-one-proof)',
  pairContext({ ...CTX_INPUT, userId: 'a'.repeat(MAX_PREFIXED_BYTES) }).length > MAX_PREFIXED_BYTES);
await throws('B4: a 256-byte phoneDeviceId throws at encode',
  () => pairContext({ ...CTX_INPUT, phoneDeviceId: OVERSIZE }), 'phoneDeviceId');
await throws('B5: a 256-byte frameType throws at encode',
  () => aad({ frameType: OVERSIZE, kid: A.kid, seq: A.seq, direction: DIR_P2C, pairEpoch: A.pairEpoch }),
  'frameType');

// ── 5. (C) the AAD is actually passed — proven by a frame that FAILS ────────
// Flipping the direction byte 0x01 -> 0x02 is a relay replaying a p2c frame as
// c2p. A silently-ignored AAD is indistinguishable from a working one on the
// happy path, so only the failure proves it.
const T = V.aead.tamper;
const tamperedAad = fromHex(A.aadHex);
eq('C: the byte under test is the direction byte', tamperedAad[T.byteIndex], T.originalByte);
tamperedAad[T.byteIndex] = T.tamperedByte;
eq('C: tamperedAadHex', toHex(tamperedAad), T.tamperedAadHex);
check('C: exactly one byte differs',
  fromHex(A.aadHex).reduce((n, b, i) => n + (b === tamperedAad[i] ? 0 : 1), 0) === 1);

{
  const subtle = globalThis.crypto.subtle;
  const key = await subtle.importKey('raw', fromHex(A.keyHex), { name: 'AES-GCM' }, false, ['decrypt']);
  const params = { name: 'AES-GCM', iv: fromHex(A.nonceHex), tagLength: 128 };
  await throws('C: the tag check FAILS under the tampered AAD',
    () => subtle.decrypt({ ...params, additionalData: tamperedAad }, key, ctA));
  // Control: the SAME call with the untampered AAD must succeed, or the
  // assertion above would pass on a decrypt that was broken for another reason.
  const good = new Uint8Array(await subtle.decrypt({ ...params, additionalData: fromHex(A.aadHex) }, key, ctA));
  eq('C control: the UNtampered AAD opens the same frame', toHex(good), A.paddedPlaintextHex);
}

// A tampered seq, kid or frameType must fail the same way — the AAD binds all
// five fields, not just the one the vector happens to flip.
for (const [name, patch] of [
  ['seq (moved to slip the §13.5 dedupe window)', { seq: A.seq + 1 }],
  ['kid (relabelled key id)', { kid: 'kid-02' }],
  ['frameType (CALL_STATUS relabelled as SMS_RECEIVED)', { frameType: 'CALL_STATUS' }],
  ['pairEpoch (replayed into another epoch)', { pairEpoch: A.pairEpoch + 1 }],
]) {
  const bad = { ...receiver };
  await throws(`C: a tampered ${name} fails the tag`, () => open({
    receiver: bad,
    frameType: patch.frameType ?? A.frameType,
    kid: patch.kid ?? A.kid,
    seq: patch.seq ?? A.seq,
    pairEpoch: patch.pairEpoch ?? A.pairEpoch,
    ciphertext: ctA,
  }));
}

// ── 6. (D) directional keys never cross ────────────────────────────────────
// k_c2p must not open a p2c frame. This is what makes a reflected frame inert:
// a frame bounced back at its sender cannot decrypt under the sender's own key.
eq('D: the vector names k_c2p', V.aead.crossDirection.keyHex, V.traffic.computerToPhoneKeyHex);
{
  // Deliberately mis-wired: the c2p key bytes with the p2c direction in the AAD,
  // which is the strongest form of the test — the AAD is RIGHT and only the key
  // is wrong, so nothing but the key can be what fails.
  const wrong = {
    direction: DIR_P2C,
    rawBytes: fromHex(V.aead.crossDirection.keyHex),
    sessionPrefix: fromHex(A.sessionPrefixHex),
  };
  await throws('D: k_c2p does NOT open vector A', () => open({
    receiver: wrong, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch, ciphertext: ctA,
  }));
  check('D: the vector declares it must not open', V.aead.crossDirection.mustOpen === false);
}

// There is no keyForDirection() to call with the wrong argument (A1 (2)): a
// caller gets .send and .recv and cannot name the other side's pair.
{
  const exported = await import('../lib/e2e/kdf.mjs');
  check('no keyForDirection-style helper is exported',
    !Object.keys(exported).some((k) => /^(keyFor|getKey|keyOf)/i.test(k)),
    Object.keys(exported).join(','));
  await throws('trafficKeys refuses an unknown role',
    () => trafficKeys({ pairingId: 'p', sessionKey: new Uint8Array(32).fill(1), context: CTX, role: 'relay' }),
    'role');
}

// ── 6a. (E/F/G/H) the DERIVED nonce prefixes — GATE1 Addendum A2 ───────────
// A1 specified a "random per (kid,direction)" prefix, which the frozen frame
// has no field to carry: undecryptable as written. A2 ratifies deriving it
// instead, the way TLS 1.3 derives its record IV and never transmits it.
//
// Vector F is the SAME frame as vector A with exactly ONE input changed — the
// prefix — so a divergence localises immediately. Vector A keeps its explicit
// prefix and is the "given a prefix, seal correctly" test; F is the "derive the
// prefix correctly" test. Both are needed.
const NP = V.noncePrefixes;
{
  eq('E: infoNp2cHex', toHex(noncePrefixInfo(CTX, DIR_P2C)), NP.infoNp2cHex);
  eq('E: infoNc2pHex', toHex(noncePrefixInfo(CTX, DIR_C2P)), NP.infoNc2pHex);
  eq('E: the labels are the ones the vectors were derived under',
    `${LABEL_NP2C}|${LABEL_NC2P}`,
    `${V.labels.noncePrefixP2c}|${V.labels.noncePrefixC2p}`);

  const { np2c, nc2p } = await deriveNoncePrefixes({
    pairingId: CTX_INPUT.pairingId, sessionKey: fromHex(V.traffic.sessionKeyHex), context: CTX,
  });
  eq('E: np2cHex', toHex(np2c), NP.np2cHex);
  eq('E: nc2pHex', toHex(nc2p), NP.nc2pHex);
  eq('E: a prefix is 4 bytes', np2c.length, NP.lengthBytes);
  eq('E: …and that is SESSION_PREFIX_BYTES', np2c.length, SESSION_PREFIX_BYTES);

  // Independently, through node:crypto — the same cross-check the keys get.
  eq('E: np2c (node:crypto, independent)',
    independentHkdf(V.traffic.sessionKeyHex, NP.infoNp2cHex).slice(0, 8), NP.np2cHex);
  // A2: "L = 4" and "expand 32 then truncate to 4" are the same bytes, because
  // HKDF-Expand emits T(1) first. Asserted so an implementation that did it the
  // other way is KNOWN conformant rather than assumed to be.
  eq('E: L=4 and truncate-32-to-4 are the same bytes',
    toHex(await hkdfBytes({
      salt: CTX_INPUT.pairingId, ikm: fromHex(V.traffic.sessionKeyHex),
      info: noncePrefixInfo(CTX, DIR_P2C), length: 32,
    })).slice(0, 8), NP.np2cHex);

  // H — the negative. A2's derivation cannot produce equal prefixes for distinct
  // labels; an implementation that fed the SAME label twice would, and that is a
  // one-character typo that nothing else here would catch.
  check('H: np2c !== nc2p', toHex(np2c) !== toHex(nc2p));
  check('H: neither prefix is all-zero',
    !np2c.every((b) => b === 0) && !nc2p.every((b) => b === 0));
  check('H: the vector declares both requirements',
    NP.negativeH.mustDiffer === true && NP.negativeH.mustNotBeAllZero === true);
  // The prefix is a function of the CONTEXT too, not only the label: a wrong
  // epoch changes it. That is what makes I.2's replay case fail on the nonce as
  // well as on the key.
  const otherEpoch = await deriveNoncePrefixes({
    pairingId: CTX_INPUT.pairingId,
    sessionKey: fromHex(V.traffic.sessionKeyHex),
    context: pairContext({ ...CTX_INPUT, pairEpoch: CTX_INPUT.pairEpoch + 1 }),
  });
  check('H: a different pairEpoch yields a different prefix', toHex(otherEpoch.np2c) !== toHex(np2c));

  // A2 MUST#2, expressed structurally: trafficKeys() hands the prefix out with
  // the key it belongs to, so a caller has nothing to persist and nothing stale
  // to restore. A prefix that arrived from storage is the one way this design
  // drifts back into the bug A2 just removed.
  eq('A2 MUST#2: trafficKeys attaches the DERIVED p2c prefix to the phone\'s send key',
    toHex(phoneKeys.send.sessionPrefix), NP.np2cHex);
  eq('A2 MUST#2: …and the c2p prefix to its receive key',
    toHex(phoneKeys.recv.sessionPrefix), NP.nc2pHex);
  eq('A2 MUST#2: the computer sees the mirror image on send',
    toHex(computerKeys.send.sessionPrefix), NP.nc2pHex);
  eq('A2 MUST#2: …and on recv', toHex(computerKeys.recv.sessionPrefix), NP.np2cHex);

  // F and G — the full frames under the derived prefixes.
  for (const [label, Vec, keys] of [['F', V.aead.vectorF, phoneKeys], ['G', V.aead.vectorG, computerKeys]]) {
    eq(`${label}: keyHex is the vector file's own traffic key`, Vec.keyHex, toHex(keys.send.rawBytes));
    eq(`${label}: the prefix is the DERIVED one`, Vec.noncePrefixHex, toHex(keys.send.sessionPrefix));
    eq(`${label}: nonceHex is prefix || be64(seq)`,
      toHex(nonce(keys.send.sessionPrefix, Vec.seq)), Vec.nonceHex);
    eq(`${label}: aadHex`, toHex(aad({
      frameType: Vec.frameType, kid: Vec.kid, seq: Vec.seq, direction: keys.send.direction, pairEpoch: Vec.pairEpoch,
    })), Vec.aadHex);
    eq(`${label}: the direction byte matches the vector`, keys.send.direction, Vec.direction);
    const ct = await seal({
      sender: keys.send, frameType: Vec.frameType, kid: Vec.kid, seq: Vec.seq, pairEpoch: Vec.pairEpoch,
      plaintext: new TextEncoder().encode(Vec.plaintextUtf8),
    });
    eq(`${label}: ciphertextHex`, toHex(ct), Vec.ciphertextHex);
    eq(`${label}: 80 bytes = 64 ciphertext || 16 tag`, ct.length, Vec.ciphertextBytes);
    // …and it opens on the OTHER side's receive half, which is the half that
    // proves key, prefix and direction all move together.
    const other = keys === phoneKeys ? computerKeys : phoneKeys;
    const opened = await open({
      receiver: other.recv, frameType: Vec.frameType, kid: Vec.kid, seq: Vec.seq,
      pairEpoch: Vec.pairEpoch, ciphertext: fromHex(Vec.ciphertextHex),
    });
    eq(`${label}: round-trips to the original plaintext`, new TextDecoder().decode(opened), Vec.plaintextUtf8);
  }
  // F and G differ in EVERY direction-carried input, which is the claim: an
  // implementation that flipped the AAD byte but kept the p2c key or the p2c
  // prefix passes F and fails only here.
  check('G: the c2p frame shares nothing with the p2c frame but the plaintext',
    V.aead.vectorF.keyHex !== V.aead.vectorG.keyHex
    && V.aead.vectorF.noncePrefixHex !== V.aead.vectorG.noncePrefixHex
    && V.aead.vectorF.aadHex !== V.aead.vectorG.aadHex
    && V.aead.vectorF.ciphertextHex !== V.aead.vectorG.ciphertextHex
    && V.aead.vectorF.paddedPlaintextHex === V.aead.vectorG.paddedPlaintextHex);
  // A and F differ in EXACTLY one input — that is what makes F a localiser.
  eq('F: the AAD is byte-identical to vector A\'s', V.aead.vectorF.aadHex, A.aadHex);
  eq('F: …and the padded plaintext too', V.aead.vectorF.paddedPlaintextHex, A.paddedPlaintextHex);
  check('F: only the prefix differs from A', V.aead.vectorF.noncePrefixHex !== A.sessionPrefixHex);
  check('F: …so the ciphertexts differ', V.aead.vectorF.ciphertextHex !== A.ciphertextHex);
}

// ── 6b. (I) ctx from the wire + the LOCAL userId — GATE1 Addendum A3 ───────
// The assertion is one sentence: wire ctx + local userId == the frozen local
// context, byte for byte. Everything else in this block is a way of proving
// that the fields which are NOT on the wire, and the parse of the one field
// whose encoding is unusual, are load-bearing rather than decorative.
{
  const W = V.ctxWire;
  const I1 = W.positiveI1;

  const r = pairContextFromWire(I1.ctxWire, { userId: I1.localUserId });
  eq('I.1: wire ctx + local userId reproduces the FROZEN context bytes',
    toHex(r.contextBytes), I1.contextBytesHex);
  eq('I.1: …which is this file\'s own contextBytesHex', I1.contextBytesHex, V.contextBytesHex);
  eq('I.1: pairEpoch is parsed as a BigInt, not a Number', typeof r.pairEpoch, 'bigint');
  eq('I.1: …with the right value', r.pairEpoch, 42n);

  const wireKeys = await trafficKeys({
    pairingId: I1.ctxWire.pairingId, sessionKey: fromHex(V.traffic.sessionKeyHex),
    context: r.contextBytes, role: 'phone',
  });
  eq('I.1: k_p2c from the wire ctx', toHex(wireKeys.send.rawBytes), I1.phoneToComputerKeyHex);
  eq('I.1: k_c2p from the wire ctx', toHex(wireKeys.recv.rawBytes), I1.computerToPhoneKeyHex);
  eq('I.1: …and they are the file\'s frozen traffic keys',
    `${I1.phoneToComputerKeyHex}|${I1.computerToPhoneKeyHex}`,
    `${V.traffic.phoneToComputerKeyHex}|${V.traffic.computerToPhoneKeyHex}`);
  eq('I.1: np2c from the wire ctx', toHex(wireKeys.send.sessionPrefix), I1.np2cHex);
  eq('I.1: nc2p from the wire ctx', toHex(wireKeys.recv.sessionPrefix), I1.nc2pHex);
  eq('I.1: …and they are A2 vector E\'s', `${I1.np2cHex}|${I1.nc2pHex}`, `${NP.np2cHex}|${NP.nc2pHex}`);

  // THE cross-implementation assertion: a ciphertext Security produced opens
  // under a key this lane derived from the WIRE form. P4 asserts I.1 through
  // its encode path (it builds ctx); P2/P3 through their decode path. That
  // pairing is what makes the vector cross-implementation rather than two
  // copies of one belief.
  check('I.1: the vector declares it opens A2 vector F', I1.opensVectorF === true);
  const openedF = await open({
    // rawBytes, not the CryptoKey: trafficKeys imports the send half with
    // ['encrypt'] usage only, so open() must import its own decrypt key.
    receiver: { direction: DIR_P2C, rawBytes: wireKeys.send.rawBytes, sessionPrefix: wireKeys.send.sessionPrefix },
    frameType: V.aead.vectorF.frameType, kid: V.aead.vectorF.kid, seq: V.aead.vectorF.seq,
    pairEpoch: V.aead.vectorF.pairEpoch, ciphertext: fromHex(V.aead.vectorF.ciphertextHex),
  });
  eq('I.1: A2 vector F opens under the WIRE-derived key and prefix',
    toHex(padPlaintext(V.aead.vectorF.frameType, openedF)), I1.openedPlaintextHex);

  // I.2 — epoch drift. The A3-M2 replay case: a relay that replays an old
  // ACCEPT_PAIRING re-installs a superseded SK under its old epoch, and the
  // per-(kid,direction) counter restarts at 0 against a key and prefix that
  // have already sealed frames. That is GCM nonce reuse, the one failure in
  // this protocol whose cost is total.
  const I2 = W.negativeI2EpochDrift;
  const r2 = pairContextFromWire({ ...I1.ctxWire, pairEpoch: I2.pairEpoch }, { userId: I1.localUserId });
  eq('I.2: one epoch changes the context bytes', toHex(r2.contextBytes), I2.contextBytesHex);
  check('I.2: …in exactly the last byte',
    I2.contextBytesHex.slice(0, -2) === I1.contextBytesHex.slice(0, -2)
    && I2.contextBytesHex.slice(-2) !== I1.contextBytesHex.slice(-2));
  const k2 = await trafficKeys({
    pairingId: I1.ctxWire.pairingId, sessionKey: fromHex(V.traffic.sessionKeyHex),
    context: r2.contextBytes, role: 'phone',
  });
  eq('I.2: k_p2c under the drifted epoch', toHex(k2.send.rawBytes), I2.phoneToComputerKeyHex);
  eq('I.2: np2c under the drifted epoch', toHex(k2.send.sessionPrefix), I2.np2cHex);
  check('I.2: the vector declares F must NOT open', I2.opensVectorF === false);
  await throws('I.2: A2 vector F FAILS authentication under the drifted epoch', () => open({
    receiver: { direction: DIR_P2C, rawBytes: k2.send.rawBytes, sessionPrefix: k2.send.sessionPrefix },
    frameType: V.aead.vectorF.frameType, kid: V.aead.vectorF.kid, seq: V.aead.vectorF.seq,
    pairEpoch: V.aead.vectorF.pairEpoch, ciphertext: fromHex(V.aead.vectorF.ciphertextHex),
  }));

  // I.3 — the un-transmitted field is load-bearing. One character of LOCAL
  // session identity, and the keys diverge completely. This is the whole reason
  // userId is not on the wire: transmitting it would let the relay propose an
  // identity, and the derivation would agree with the relay instead of with the
  // authenticated session.
  const I3 = W.negativeI3UserIdDrift;
  const r3 = pairContextFromWire(I1.ctxWire, { userId: I3.localUserId });
  const k3 = await trafficKeys({
    pairingId: I1.ctxWire.pairingId, sessionKey: fromHex(V.traffic.sessionKeyHex),
    context: r3.contextBytes, role: 'phone',
  });
  eq('I.3: a one-character local userId drift changes k_p2c',
    toHex(k3.send.rawBytes), I3.phoneToComputerKeyHex);
  check('I.3: …to something completely different from I.1',
    I3.phoneToComputerKeyHex !== I1.phoneToComputerKeyHex && I3.mustDifferFromI1 === true);
  check('I.3: the wire ctx was byte-identical — only the LOCAL field moved',
    JSON.stringify(I1.ctxWire) === JSON.stringify(I1.ctxWire)
    && I1.localUserId !== I3.localUserId);

  // I.4 — every one of these MUST throw at ingest, never coerce. Each is a
  // value that would otherwise turn into a plausible-looking epoch and derive a
  // key nobody else holds.
  const I4 = W.negativeI4Parser;
  for (const bad of I4.badPairEpoch) {
    await throws(`I.4: pairEpoch ${JSON.stringify(bad)} is refused`,
      () => pairContextFromWire({ ...I1.ctxWire, pairEpoch: bad }, { userId: I1.localUserId }),
      'pairEpoch');
  }
  check('I.4: the JSON-number case really is a number', typeof I4.badPairEpoch[0] === 'number');
  // The regex is A3's, character for character. A looser one (say `^[0-9]+$`)
  // would accept "042" and " 42" is only excluded by the anchors — so the
  // pattern itself is pinned, not merely its effect on this sample.
  eq('I.4: the epoch pattern is A3\'s, exactly',
    String(PAIR_EPOCH_WIRE_RE), '/^(0|[1-9][0-9]{0,19})$/');
  {
    const noEpoch = { ...I1.ctxWire };
    delete noEpoch.pairEpoch;
    await throws('I.4: an absent pairEpoch is refused',
      () => pairContextFromWire(noEpoch, { userId: I1.localUserId }), 'pairEpoch');
    check('I.4: the vector declares the missing-epoch case', I4.missingPairEpoch === true);
  }
  // A3-M4: no ctx at all on a mode=1 block. Refusing is the whole point —
  // deriving from a locally guessed context is precisely the silent divergence
  // A3 exists to kill, and it would let a STRIPPING relay force both sides into
  // a guess. The error must name A3-M4 so nobody "fixes" it with a fallback.
  check('I.4: the vector declares the missing-ctx case', I4.missingCtxOnMode1 === true);
  for (const absent of [undefined, null]) {
    await throws(`I.4: ctx ${String(absent)} on a mode=1 block is REFUSED, never derived from local`,
      () => pairContextFromWire(absent, { userId: I1.localUserId }), 'A3-M4');
  }
  await throws('I.4: a ctx that is not an object is refused',
    () => pairContextFromWire('nope', { userId: I1.localUserId }), 'object');
  await throws('I.4: an array is not an object here either',
    () => pairContextFromWire([], { userId: I1.localUserId }), 'object');

  // I.4's peerDeviceId-mismatch case was A3-M3's "must be my own deviceId"
  // refusal. A4 DELETED that clause, so the case is re-pointed rather than
  // dropped: the same fixture ids now prove the clause is GONE — passing
  // `deviceId` throws as an unknown option, and the value it used to reject is
  // accepted when it is the canonical peer of the set it belongs to. Section 6c
  // carries the replacement checks.
  await throws('I.4 (A4): `deviceId` is REJECTED, not ignored — the A3-M3 self-check is deleted',
    () => pairContextFromWire(I1.ctxWire, {
      userId: I1.localUserId, deviceId: I4.peerDeviceIdMismatch.ownDeviceId,
    }), 'A4-M1');
  check('I.4 (A4): with no deviceId and no set, I.1 still derives the frozen bytes',
    toHex(pairContextFromWire(I1.ctxWire, { userId: I1.localUserId }).contextBytes)
      === I1.contextBytesHex);
  await throws('I.4: a pairingId that is not ours is refused (A3-M3)',
    () => pairContextFromWire(
      { ...I1.ctxWire, pairingId: I4.pairingIdMismatch.ctxPairingId },
      { userId: I1.localUserId, pairingId: I4.pairingIdMismatch.ownPairingId },
    ), 'A3-M3');
  check('I.4 control: the MATCHING pairingId is accepted',
    pairContextFromWire(I1.ctxWire, {
      userId: I1.localUserId, pairingId: I4.pairingIdMismatch.ownPairingId,
    }).pairingId === I1.ctxWire.pairingId);

  // A1's encode-time u8 cap, re-asserted on the DECODE side. A 256-byte id
  // arriving from the wire must be refused, not truncated to `len & 0xff`.
  const OVER = 'a'.repeat(I4.oversizeFieldBytes);
  for (const f of I4.oversizeFields) {
    if (f === 'userId') {
      await throws(`I.4: a ${I4.oversizeFieldBytes}-byte LOCAL userId is refused at decode`,
        () => pairContextFromWire(I1.ctxWire, { userId: OVER }), 'userId');
    } else {
      await throws(`I.4: a ${I4.oversizeFieldBytes}-byte ctx.${f} is refused at decode`,
        () => pairContextFromWire({ ...I1.ctxWire, [f]: OVER }, { userId: I1.localUserId }), f);
    }
  }
  // The local userId is never taken from the wire — an absent one must throw
  // rather than fall back to anything the ctx happens to carry.
  await throws('I.4: no LOCAL userId -> refuse (it is never read off the wire)',
    () => pairContextFromWire(I1.ctxWire, {}), 'userId');
  await throws('I.4: a ctx field that is not a string is refused',
    () => pairContextFromWire({ ...I1.ctxWire, phoneDeviceId: 7 }, { userId: I1.localUserId }),
    'phoneDeviceId');
  // 2^64 is out of range; 2^64-1 is the largest legal epoch.
  await throws('I.4: a pairEpoch above 2^64-1 is refused',
    () => pairContextFromWire({ ...I1.ctxWire, pairEpoch: '18446744073709551616' }, { userId: I1.localUserId }),
    '2^64');
  check('I.4 control: 2^64-1 is accepted and does not round',
    toHex(pairContextFromWire({ ...I1.ctxWire, pairEpoch: '18446744073709551615' }, { userId: I1.localUserId })
      .contextBytes).endsWith('ffffffffffffffff'));
}

// ── 6c. (A4) the canonical peer — GATE1 Addendum A4, module behaviour ──────
// A4 resolves a contradiction between two A3 MUSTs. A3-M1 froze `ctx` as
// PAIR-scoped ("every recipient gets the identical object"); A3-M3 then made a
// receiver refuse any block whose `ctx.peerDeviceId` was not its own. Together
// those two admit at most ONE recipient, which is not a costlier multi-recipient
// pairing — it is no multi-recipient pairing at all. This block pins the
// deletion (A4-M1) and the rule that replaces it (A4-R2), with no frozen bytes:
// section 6d does the bytes, against Security's independently computed vector J.
{
  // Deliberately ordered so the canonical lowest is NOT first in array order —
  // an implementation that returned `wraps[0]` would pass a same-order fixture.
  const WRAPS = [{ deviceId: 'dev-web-01', wrap: 'x' }, { deviceId: 'dev-ext-02', wrap: 'y' }];
  const CANON = 'dev-ext-02';

  eq('A4-R2: the canonical peer is the byte-wise lowest, not wraps[0]',
    canonicalPeerDeviceId(WRAPS), CANON);
  eq('A4-R2: …and it is ORDER-INDEPENDENT (a re-ordering relay cannot steer)',
    canonicalPeerDeviceId([...WRAPS].reverse()), CANON);
  eq('A4-R2: a bare deviceId[] is accepted as well as wraps[]',
    canonicalPeerDeviceId(['dev-web-01', 'dev-ext-02']), CANON);

  // UTF-8 BYTES, not UTF-16 code units. This pair is the case where `a < b` on
  // JS strings and byte order DISAGREE: U+10000 encodes to f0 90 80 80, which is
  // ABOVE U+FF00's ef bc 80 in UTF-8, while its leading surrogate D800 is BELOW
  // FF00 in UTF-16. A `<`-based implementation picks the other id here, and two
  // lanes that disagree about the canonical peer both fail closed with a tag
  // error and no attribution — the exact silent break A4-M5 exists to name.
  {
    const hi = `d-\u{10000}`;      // f0 90 80 80  — HIGHER byte-wise
    const lo = 'd-＀';         // ef bc 80     — LOWER  byte-wise
    check('A4-R2: the fixture really does split UTF-8 from UTF-16 order',
      (hi < lo) && !(new TextEncoder().encode(hi)[2] < new TextEncoder().encode(lo)[2]),
      `JS-< says ${hi < lo}`);
    eq('A4-R2: the lowest is chosen by UTF-8 BYTES, not by JS string order',
      canonicalPeerDeviceId([hi, lo]), lo);
  }

  // Uniqueness is what makes "lowest" a TOTAL order. validateE2eBlock already
  // proves it (lib/e2eBlock-core.js:169-173); re-asserted because a duplicate
  // would make "the canonical peer" a coin flip rather than a rule.
  await throws('A4-R2: a duplicate deviceId is refused — "lowest" must be total',
    () => canonicalPeerDeviceId(['dev-a', 'dev-a']), 'duplicate');
  await throws('A4-R2: an empty set has no canonical peer', () => canonicalPeerDeviceId([]), 'non-empty');
  await throws('A4-R2: a non-array is refused', () => canonicalPeerDeviceId('dev-a'), 'non-empty');
  await throws('A4-R2: a deviceId over the u8 byte cap is refused at selection',
    () => canonicalPeerDeviceId(['dev-a', 'b'.repeat(MAX_PREFIXED_BYTES + 1)]), 'u8 cap');

  const CTXW = { pairingId: 'pair-7f3a9c21', phoneDeviceId: 'dev-phone-01', peerDeviceId: CANON, pairEpoch: '42' };
  const LOCAL_USER = 'user-0191aa';

  // A4-M1, the deletion. The option is REJECTED rather than ignored: a caller
  // still passing `deviceId` believes a membership check is running, and
  // silently dropping it would leave that belief intact with the check gone.
  await throws('A4-M1: `deviceId` throws — the self-check is deleted, not relaxed',
    () => pairContextFromWire(CTXW, { userId: LOCAL_USER, deviceId: 'dev-web-01' }), 'A4-M1');

  // J.5 — THE REGRESSION THIS ADDENDUM IS FOR. Under the pre-A4 rule this exact
  // block refused dev-web-01 while admitting dev-ext-02. Both recipients must
  // now be admitted by the SAME block, and must derive the SAME context bytes.
  const asPage = pairContextFromWire(CTXW, { userId: LOCAL_USER, recipientDeviceIds: WRAPS });
  const asSw = pairContextFromWire(CTXW, { userId: LOCAL_USER });   // PAIR_STATE lane: no set
  check('J.5: the NON-canonical recipient (dev-web-01) is admitted by this block',
    toHex(asPage.contextBytes).length > 0);
  eq('J.5: page and SW derive BYTE-IDENTICAL context bytes (ctx is pair-scoped)',
    toHex(asPage.contextBytes), toHex(asSw.contextBytes));

  // A3-M3(c), re-scoped — enforced ONLY where the set is held.
  await throws('A3-M3(c): a steered non-canonical peer is refused where wraps[] is held',
    () => pairContextFromWire({ ...CTXW, peerDeviceId: 'dev-web-01' },
      { userId: LOCAL_USER, recipientDeviceIds: WRAPS }), 'canonical');
  check('A3-M3(c) CONTROL: the SAME steered ctx is ACCEPTED without the set (PAIR_STATE lane)',
    toHex(pairContextFromWire({ ...CTXW, peerDeviceId: 'dev-web-01' },
      { userId: LOCAL_USER }).contextBytes).includes('6465762d7765622d3031'));
  // The control above is the whole point of (c) being conditional: the SW lane
  // MUST NOT attempt it and MUST NOT substitute its own deviceId. Its binding
  // check is (b) — the wrap opening under its own KEK — which lives at unwrap,
  // not here, and whose failure is a PAIRING ABORT, never a counts-only degrade
  // (A4-M3). §13.2 row 2 grants that degrade only to a recipient that never had
  // a key; the wrap-open failure is a tampered or mismatched pairing.

  // A3-M3(a) survives A4 unchanged, and is still only checked where the
  // receiver independently knows the pairing it is party to.
  await throws('A3-M3(a): a foreign pairingId is refused (J.2)',
    () => pairContextFromWire({ ...CTXW, pairingId: 'pair-DEADBEEF' },
      { userId: LOCAL_USER, pairingId: 'pair-7f3a9c21' }), 'pairingId');
}

// ── 6d. (J) the frozen A4 vector, through the real module ──────────────────
// 6c pinned the RULE with no frozen bytes. This block pins the BYTES, against
// values Security computed in a clean-room HKDF/GCM implementation that imports
// nothing from lib/e2e/kdf.mjs — so agreement here is cross-implementation
// evidence, not one implementation agreeing with itself.
{
  const J = V.canonicalPeer;
  const J1 = J.positiveJ1;
  const SK = fromHex(V.traffic.sessionKeyHex);

  eq('J: the canonical peer of the frozen wraps[] is the vector\'s',
    canonicalPeerDeviceId(J.wraps), J.canonicalPeerDeviceId);
  check('J: the fixture\'s canonical peer is NOT wraps[0] (so wraps[0] cannot pass)',
    J.wraps[0].deviceId !== J.canonicalPeerDeviceId, J.wraps[0].deviceId);
  eq('J: ctx.peerDeviceId IS that canonical peer', J1.ctxWire.peerDeviceId, J.canonicalPeerDeviceId);

  // The page lane holds wraps[]; the SW lane (PAIR_STATE) does not. Both must
  // reach the SAME bytes — that is the whole ruling in one assertion.
  const page = pairContextFromWire(J1.ctxWire, { userId: J.localUserId, recipientDeviceIds: J.wraps });
  const sw = pairContextFromWire(J1.ctxWire, { userId: J.localUserId });
  eq('J.1: the page lane reproduces the frozen context bytes',
    toHex(page.contextBytes), J1.contextBytesHexPage);
  eq('J.1: the SW lane reproduces them too', toHex(sw.contextBytes), J1.contextBytesHexSw);
  check('J.1: the vector asserts the two are IDENTICAL, not merely both present',
    J1.contextsIdentical === true && J1.contextBytesHexPage === J1.contextBytesHexSw);
  eq('J.1: …and this lane agrees', toHex(page.contextBytes), toHex(sw.contextBytes));

  const kPage = await trafficKeys({ pairingId: J1.ctxWire.pairingId, sessionKey: SK, context: page.contextBytes, role: 'phone' });
  const kSw = await trafficKeys({ pairingId: J1.ctxWire.pairingId, sessionKey: SK, context: sw.contextBytes, role: 'phone' });
  eq('J.1: k_p2c', toHex(kPage.send.rawBytes), J1.phoneToComputerKeyHex);
  eq('J.1: k_c2p', toHex(kPage.recv.rawBytes), J1.computerToPhoneKeyHex);
  eq('J.1: np2c', toHex(kPage.send.sessionPrefix), J1.np2cHex);
  eq('J.1: nc2p', toHex(kPage.recv.sessionPrefix), J1.nc2pHex);
  eq('J.1: the SW lane derives the SAME traffic key set (one key set per pairing)',
    `${toHex(kSw.send.rawBytes)}|${toHex(kSw.recv.rawBytes)}|${toHex(kSw.send.sessionPrefix)}`,
    `${toHex(kPage.send.rawBytes)}|${toHex(kPage.recv.rawBytes)}|${toHex(kPage.send.sessionPrefix)}`);
  // J's keys must NOT be I's: if they were, the two-recipient fixture would be
  // proving nothing that vector I does not already prove.
  check('J.1: a two-recipient pairing derives DIFFERENT keys from the one-recipient I.1',
    J1.phoneToComputerKeyHex !== V.ctxWire.positiveI1.phoneToComputerKeyHex);

  // J.1b — ONE broadcast ciphertext opens for BOTH recipients. This is the
  // property a device-scoped ctx would destroy: the relay sends one ciphertext
  // byte-identically to every listener, so under per-recipient traffic keys it
  // would open for exactly one and hand the other a GCM tag failure that is
  // indistinguishable from a network fault. Raw WebCrypto, not seal/open: J
  // deliberately fixes an EMPTY AAD and an unpadded plaintext so it stands
  // alone and does not re-pin A2's frame header.
  {
    const B = J.positiveJ1bBroadcast;
    const ct = fromHex(B.ciphertextHex);
    const iv = new Uint8Array(12);
    iv.set(kPage.send.sessionPrefix, 0);
    new DataView(iv.buffer).setBigUint64(4, BigInt(B.seq));
    for (const [who, keys] of [['page', kPage], ['sw', kSw]]) {
      const ck = await crypto.subtle.importKey('raw', keys.send.rawBytes, 'AES-GCM', false, ['decrypt']);
      const pt = new Uint8Array(await crypto.subtle.decrypt(
        { name: 'AES-GCM', iv, additionalData: new Uint8Array(0), tagLength: 128 }, ck, ct));
      eq(`J.1b: the ONE broadcast ciphertext opens for the ${who}`,
        new TextDecoder().decode(pt), who === 'page' ? B.opensForPage : B.opensForSw);
    }
  }

  // J.1c — per-recipient KEKs DIFFER from the same ctx. This is why one shared
  // traffic-key set costs nothing: separation still lives in the KEK, which
  // binds the recipient's own static key on top of the shared context.
  {
    const C = J.positiveJ1cKeks;
    const kekWeb = await kek({ pairingId: J1.ctxWire.pairingId, sharedSecret: SK, context: page.contextBytes, recipientKey: fromHex(C.webKeyHex) });
    const kekExt = await kek({ pairingId: J1.ctxWire.pairingId, sharedSecret: SK, context: sw.contextBytes, recipientKey: fromHex(C.extKeyHex) });
    eq('J.1c: KEK_web', toHex(kekWeb), C.kekWebHex);
    eq('J.1c: KEK_ext', toHex(kekExt), C.kekExtHex);
    check('J.1c: the KEKs DIFFER although the ctx is identical',
      toHex(kekWeb) !== toHex(kekExt) && C.keksDiffer === true);
  }

  // J.2 / J.3 — the refusals, at ingest, before any derivation.
  {
    const P = J.negativeJ2PairingId;
    await throws('J.2: a foreign ctx.pairingId is refused where we know ours',
      () => pairContextFromWire({ ...J1.ctxWire, pairingId: P.ctxPairingId },
        { userId: J.localUserId, pairingId: P.ownPairingId }), 'pairingId');
  }
  {
    const S = J.negativeJ3SteeredPeer;
    const steeredCtx = { ...J1.ctxWire, peerDeviceId: S.ctxPeerDeviceId };
    await throws('J.3: a relay-steered non-canonical peer is refused where wraps[] is held',
      () => pairContextFromWire(steeredCtx, { userId: J.localUserId, recipientDeviceIds: J.wraps }), 'canonical');
    // What the steered context WOULD have derived — and why refusing it early
    // matters: the derivation succeeds, it is simply the wrong key, which is a
    // silent break unless something refuses before the first frame.
    const steered = pairContextFromWire(steeredCtx, { userId: J.localUserId });
    eq('J.3: the steered context bytes', toHex(steered.contextBytes), S.contextBytesHex);
    const kSteer = await trafficKeys({ pairingId: J1.ctxWire.pairingId, sessionKey: SK, context: steered.contextBytes, role: 'phone' });
    eq('J.3: the steered k_p2c', toHex(kSteer.send.rawBytes), S.phoneToComputerKeyHex);
    check('J.3: …which is NOT J.1\'s key', S.phoneToComputerKeyHex !== J1.phoneToComputerKeyHex);

    // SINGLE-RECIPIENT INVARIANCE — the proof that A4 rekeys nothing already
    // shipped. For a one-recipient pairing the canonical lowest IS that
    // recipient, so the steered context (peer forced to dev-web-01, the sole
    // recipient of vector I) must reproduce I.1's frozen key EXACTLY. Two
    // independent clean-room implementations agree on it; A4 adds no row to
    // E-H or I and forces no re-pair.
    eq('J.3: the steered k_p2c IS vector I.1\'s frozen key — single-recipient unchanged',
      S.phoneToComputerKeyHex, V.ctxWire.positiveI1.phoneToComputerKeyHex);
    eq('J.3: …and the steered context bytes ARE I.1\'s', S.contextBytesHex, V.ctxWire.positiveI1.contextBytesHex);
    eq('J.3: …which are this file\'s own frozen contextBytesHex', S.contextBytesHex, V.contextBytesHex);
    eq('J.3: a ONE-recipient pairing selects its sole recipient as canonical',
      canonicalPeerDeviceId([{ deviceId: S.ctxPeerDeviceId }]), S.ctxPeerDeviceId);

    // J.1b's ciphertext MUST FAIL authentication under the steered key. A
    // steered derivation that merely "looked different" would prove nothing.
    {
      const B = J.positiveJ1bBroadcast;
      const iv = new Uint8Array(12);
      iv.set(kSteer.send.sessionPrefix, 0);
      new DataView(iv.buffer).setBigUint64(4, BigInt(B.seq));
      const ck = await crypto.subtle.importKey('raw', kSteer.send.rawBytes, 'AES-GCM', false, ['decrypt']);
      await throws('J.3: the J.1b broadcast FAILS authentication under the steered key',
        () => crypto.subtle.decrypt({ name: 'AES-GCM', iv, additionalData: new Uint8Array(0), tagLength: 128 },
          ck, fromHex(B.ciphertextHex)));
      check('J.3: the vector declares that failure', S.j1bCiphertextMustFailAuth === true);
    }
  }

  // J.4 — the non-member. Its KEK is a real, derivable value; what refuses it
  // is that no wraps[] entry opens under it. A4-M3: that is a PAIRING ABORT,
  // never a degrade to counts-only badges.
  {
    const N = J.negativeJ4NonMember;
    const outsiderKey = fromHex('04' + '00'.repeat(64));
    check('J.4: the vector pins the outsider KEK', /^[0-9a-f]{64}$/.test(N.outsiderKekHex));
    check('J.4: the outsider is not in wraps[]',
      !J.wraps.some((w) => w.deviceId === 'dev-outsider-03'));
    check('J.4: …so it cannot be the canonical peer either',
      canonicalPeerDeviceId([...J.wraps, { deviceId: 'dev-outsider-03' }]) === J.canonicalPeerDeviceId);
    check('J.4 shape control: a well-formed foreign key still derives A kek (the refusal is the UNWRAP, not the derive)',
      outsiderKey.length === SEC1_P256_BYTES);
  }

  // J.5 — the regression, stated against the frozen fixture rather than inline.
  {
    const R = J.negativeJ5PreA4Regression;
    eq('J.5: the pre-A4 rule refused the NON-canonical recipient', R.preA4RefusedDeviceId, 'dev-web-01');
    eq('J.5: …and admitted only the canonical one', R.preA4AdmittedDeviceId, J.canonicalPeerDeviceId);
    check('J.5: after A4 BOTH are admitted by the same block', R.bothMustBeAdmittedAfterA4 === true);
    for (const w of J.wraps) {
      // There is no longer any per-recipient input at all — which is exactly
      // how "both recipients are admitted" is expressed after A4.
      eq(`J.5: the block derives the frozen context for ${w.deviceId}`,
        toHex(pairContextFromWire(J1.ctxWire, { userId: J.localUserId, recipientDeviceIds: J.wraps }).contextBytes),
        J1.contextBytesHexPage);
    }
  }
}

// ── 7. persist-before-emit / FAIL CLOSED (A1 (3)) ──────────────────────────
// The rule A1 calls the single most likely one to be quietly skipped, so it is
// a constructor precondition rather than a comment — and therefore testable.
{
  const committed = [];
  const s = createSender({
    trafficKey: phoneKeys.send,
    sessionPrefix: fromHex(A.sessionPrefixHex),
    resumeFrom: 0,
    commitSeq: async (next) => { committed.push(next); },
  });
  const first = await s.nextSeq();
  const second = await s.nextSeq();
  eq('the counter starts at the proven floor', first, 0n);
  eq('the counter strictly increments', second, 1n);
  check('the NEXT value was durably committed before the seq was handed out',
    committed.length === 2 && committed[0] === 1n && committed[1] === 2n, committed.join(','));

  await throws('FAIL CLOSED: no proven counter floor -> refuse to encrypt',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex), commitSeq: async () => {},
    }), 'rekey');
  await throws('FAIL CLOSED: no durable commit -> refuse to encrypt',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex), resumeFrom: 0,
    }), 'commitSeq');
  await throws('a sessionPrefix of the wrong width is refused',
    () => createSender({
      trafficKey: phoneKeys.send, sessionPrefix: new Uint8Array(SESSION_PREFIX_BYTES + 1),
      resumeFrom: 0, commitSeq: async () => {},
    }), 'sessionPrefix');
  // A restored device that resumes ABOVE its floor is fine; the rule is that it
  // must PROVE the floor, not that the counter may never jump.
  const restored = createSender({
    trafficKey: phoneKeys.send, sessionPrefix: fromHex(A.sessionPrefixHex),
    resumeFrom: 9000, commitSeq: async () => {},
  });
  eq('a restored sender resumes at its proven floor, never at 0', await restored.nextSeq(), 9000n);
}

// ── 8. malformed input fails loudly rather than deriving something ─────────
await throws('a K_i that is not 65 bytes is refused at import',
  () => kekInfo(CTX, '04' + 'aa'.repeat(63)), '65');
await throws('a 65-byte K_i that is not 0x04-prefixed is refused',
  () => kekInfo(CTX, '02' + 'aa'.repeat(64)), '0x04');
await throws('an all-zero shared secret is refused',
  () => kek({ pairingId: 'p', sharedSecret: new Uint8Array(32), context: CTX, recipientKey: V.kek.recipients[0].publicKeySec1Hex }),
  'all-zero');
await throws('an empty pairingId is refused (it is the HKDF salt)',
  () => trafficKeys({ pairingId: '', sessionKey: fromHex(V.traffic.sessionKeyHex), context: CTX, role: 'phone' }),
  'pairingId');
await throws('a direction byte outside {0x01,0x02} is refused',
  () => aad({ frameType: A.frameType, kid: A.kid, seq: A.seq, direction: 0x03, pairEpoch: A.pairEpoch }),
  'direction');
await throws('a negative pairEpoch is refused',
  () => pairContext({ ...CTX_INPUT, pairEpoch: -1 }), 'uint64');
// be64 is BigInt, not a JS number: a value above 2^53 must not silently round.
check('be64 does not round above 2^53',
  toHex(pairContext({ ...CTX_INPUT, pairEpoch: 9007199254740993n })).endsWith('20000000000001'),
  toHex(pairContext({ ...CTX_INPUT, pairEpoch: 9007199254740993n })).slice(-16));

// ── 9. the framing actually disambiguates ──────────────────────────────────
// Without the tags and u8 length prefixes, ("ab","cd") and ("a","bcd") flatten
// to the same context bytes and two different pairings derive the SAME traffic
// keys. This is the bug the whole section exists for.
{
  const base = { peerDeviceId: 'x', pairEpoch: 1 };
  const one = toHex(pairContext({ ...base, userId: 'ab', phoneDeviceId: 'cd' }));
  const two = toHex(pairContext({ ...base, userId: 'a', phoneDeviceId: 'bcd' }));
  check('("ab","cd") and ("a","bcd") produce DIFFERENT context bytes', one !== two, `both are ${one}`);
}
// Tag ranges are disjoint — a SAS transcript can never be replayed as a KDF
// info string. The SAS uses 0x01..0x04; nothing here may.
{
  const tags = [0x11, 0x12, 0x13, 0x14, 0x15, 0x21, 0x22, 0x23, 0x24, 0x25];
  check('no KDF/AEAD tag falls in the SAS range 0x01..0x04', tags.every((t) => t > 0x04));
  check('the KDF and AEAD ranges do not overlap', new Set(tags).size === tags.length);
}

// ── 10. DRIFT GUARD: the spec text and the module must agree ───────────────
// The web/SW lane's equivalent of Android's E2eKdfVectorsTest drift assertion.
// The layout is re-encoded from the constants written in §13.10 of the SPEC —
// parsed out of the markdown, NOT imported from the module — so an edit to
// lib/e2e/kdf.mjs that nobody mirrored into the spec (or the reverse) fails
// here rather than at a pairing.
{
  const specText = readFileSync(SPEC, 'utf8');
  const section = specText.slice(specText.indexOf('### 13.10 Key schedule + AEAD'));
  check('§13.10 exists in the spec', section.length > 0);
  check('§13 names A1 as the amending authority', /AMENDING AUTHORITY/.test(specText));
  check('§13.10 records that A1 calls it §13.9', /A1's own text calls the new section "§13\.9"/.test(specText));

  // Pull the tag bytes out of the spec's own fenced layout blocks. The blocks
  // are located by content, not by position, and `pairEpoch` is read from EACH
  // block separately: it is tagged 0x14 in the pair context and 0x25 in the
  // AAD, and a parser that found only the first would happily "confirm" a spec
  // that had lost the AAD's epoch binding entirely.
  const blocks = section.match(/```[\s\S]*?```/g) || [];
  const ctxBlock = blocks.find((b) => b.includes('pairContext =')) || '';
  const aadBlock = blocks.find((b) => b.includes('AAD =')) || '';
  check('drift guard: §13.10 carries a pairContext block and an AAD block',
    ctxBlock.length > 0 && aadBlock.length > 0);

  const tagIn = (block, pattern) => {
    const m = block.match(new RegExp(`(0x[0-9a-f]{2}) ${pattern}`));
    return m ? m[1] : null;
  };
  const specTag = (block, label) => tagIn(block, `u8\\(len\\) ${label}\\b`);
  const specTags = {
    userId: specTag(ctxBlock, 'userId'),
    phoneDeviceId: specTag(ctxBlock, 'phoneDeviceId'),
    peerDeviceId: specTag(ctxBlock, 'peerDeviceId'),
    pairEpoch: tagIn(ctxBlock, 'be64\\(pairEpoch\\)'),
    recipientKey: tagIn(ctxBlock, 'u8\\(65\\) K_i'),
    frameType: specTag(aadBlock, 'frameType'),
    kid: specTag(aadBlock, 'kid'),
    seq: tagIn(aadBlock, 'be64\\(seq\\)'),
    direction: tagIn(aadBlock, 'u8 direction'),
    aadPairEpoch: tagIn(aadBlock, 'be64\\(pairEpoch\\)'),
  };
  eq('drift guard: the AAD epoch tag is 0x25, not the context\'s 0x14',
    specTags.aadPairEpoch !== specTags.pairEpoch, true);
  for (const [name, v] of Object.entries(specTags)) {
    check(`drift guard: §13.10 states a tag for ${name}`, /^0x[0-9a-f]{2}$/.test(String(v)), String(v));
  }

  // Re-encode pairContext from the SPEC's tags, independently of kdf.mjs.
  const te = new TextEncoder();
  const u8len = (tag, s) => {
    const b = te.encode(s);
    return [tag, b.length, ...b];
  };
  const be64n = (n) => {
    const out = [];
    let v = BigInt(n);
    for (let i = 7; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
    return out;
  };
  const specContext = Uint8Array.from([
    ...u8len(parseInt(specTags.userId, 16), CTX_INPUT.userId),
    ...u8len(parseInt(specTags.phoneDeviceId, 16), CTX_INPUT.phoneDeviceId),
    ...u8len(parseInt(specTags.peerDeviceId, 16), CTX_INPUT.peerDeviceId),
    parseInt(specTags.pairEpoch, 16), ...be64n(CTX_INPUT.pairEpoch),
  ]);
  eq('drift guard: the spec text re-encodes to the module\'s pairContext bytes',
    toHex(specContext), toHex(CTX));
  eq('drift guard: …and to the frozen vector', toHex(specContext), V.contextBytesHex);

  const specAad = Uint8Array.from([
    ...u8len(parseInt(specTags.frameType, 16), A.frameType),
    ...u8len(parseInt(specTags.kid, 16), A.kid),
    parseInt(specTags.seq, 16), ...be64n(A.seq),
    parseInt(specTags.direction, 16), A.direction,
    parseInt(specTags.aadPairEpoch, 16), ...be64n(A.pairEpoch),
  ]);
  eq('drift guard: the spec text re-encodes to the module\'s AAD bytes', toHex(specAad), toHex(aadA));

  // The reserved-range table is a freeze condition, not decoration.
  for (const range of ['`0x01..0x04`', '`0x11..0x15`', '`0x21..0x25`']) {
    check(`drift guard: §13.10.1 reserves ${range}`, section.includes(range));
  }
  check('drift guard: §13.10 keeps the labels the vectors were derived under',
    section.includes('"cc-e2e-v1/kek"') && section.includes('"cc-e2e-v1/p2c"') && section.includes('"cc-e2e-v1/c2p"'));

  // A2 and A3 land in the spec as §13.10.7 and §13.10.8. Same principle as the
  // tag guard above: an addendum that changed the module but never reached the
  // spec (or the reverse) fails here rather than at a pairing.
  {
    const a2 = section.slice(section.indexOf('#### 13.10.7'), section.indexOf('#### 13.10.8'));
    const a3 = section.slice(section.indexOf('#### 13.10.8'));
    check('drift guard: §13.10.7 exists (A2)', a2.length > 0);
    check('drift guard: §13.10.8 exists (A3)', a3.length > 0);
    check('drift guard: §13.10.7 carries the nonce-prefix labels the vectors were derived under',
      a2.includes(`"${LABEL_NP2C}"`) && a2.includes(`"${LABEL_NC2P}"`));
    check('drift guard: §13.10.7 states L = 4', /L = 4/.test(a2));
    // A2 withdrew A1's rationale, and the withdrawal is the load-bearing part:
    // a spec that kept "defence in depth" would leave rule 3 looking optional.
    check('drift guard: §13.10.7 records that the prefix contributes ZERO uniqueness',
      /zero nonce-uniqueness/i.test(a2));
    check('drift guard: §13.10.7 names rule 3 the SOLE control',
      /SOLE control against nonce reuse/.test(a2));
    check('drift guard: §13.10.7 carries A2 MUST#1 (kid <-> SK strictly 1:1)',
      /strictly 1:1/.test(a2));
    check('drift guard: §13.10.7 carries A2 MUST#2 (never persisted)',
      /never persisted/.test(a2));
    check('drift guard: §13.10.5 rule 2 no longer calls the prefix defence in depth',
      !/defence in depth against a state-restore bug\.\s+Anyone/.test(section));

    // A3: the wire form, the decimal-string rule, and all four MUSTs by name.
    for (const field of ['pairingId', 'phoneDeviceId', 'peerDeviceId', 'pairEpoch']) {
      check(`drift guard: §13.10.8 states ctx.${field}`, a3.includes(field));
    }
    check('drift guard: §13.10.8 pins pairEpoch as a DECIMAL STRING',
      /DECIMAL STRING/.test(a3) && a3.includes('^(0|[1-9][0-9]{0,19})$'));
    eq('drift guard: the spec\'s epoch pattern is the module\'s',
      a3.includes(String(PAIR_EPOCH_WIRE_RE).slice(1, -1)), true);
    check('drift guard: §13.10.8 records that userId stays LOCAL',
      /not transmitted/.test(a3));
    for (const must of ['A3-M1', 'A3-M2', 'A3-M3', 'A3-M4']) {
      check(`drift guard: §13.10.8 carries ${must}`, a3.includes(must));
    }
    check('drift guard: §13.10.8 states the A3-M1 splice as code',
      a3.includes('ctx: block.ctx'));
    check('drift guard: §13.10.8 records that ctx is a precondition of the SAS',
      /SAS computable on the computer side at all/.test(a3));
    check('drift guard: §13.10.8 records persist-before-use for the floor',
      /persist-before-use/.test(a3));
    // Control: these slices must be capable of failing.
    check('drift guard control: a MUST the addenda do NOT define is absent',
      !a3.includes('A3-M9') && !a2.includes('A2 MUST#7'));
  }
  // Control: the parser must be capable of failing. If the section slice were
  // empty or the regexes matched nothing, every assertion above would be
  // vacuously green on a spec that says nothing at all.
  check('drift guard control: a tag the spec does NOT state parses as null',
    specTag('somethingTheSpecNeverMentions') === null);
}

// ── 11. the module is service-worker clean, statically ─────────────────────
{
  // Comments are stripped FIRST. The module's own header explains that it must
  // not touch `window` or `document`; a grep over the raw source matches that
  // prose and fails a module that is in fact clean.
  const src = readFileSync(KDF_MODULE, 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
  check('kdf.mjs imports no Node built-in', !/from\s+['"]node:/.test(src));
  check('kdf.mjs touches no DOM global', !/\b(window|document|localStorage)\b/.test(src));
  check('kdf.mjs imports only ./padding.mjs',
    (src.match(/^import .*$/gm) || []).every((l) => l.includes('./padding.mjs')));
  check('the comment-stripper did not empty the file', /export function pairContext/.test(src));
}

// ── 12. …and dynamically: the same vectors, under SW constraints ───────────
// `process`, `Buffer` and `require` are removed and `self` is bound to the
// global before the module is imported, which is the shape an MV3 service
// worker presents. A module that reached for any of them would throw here and
// pass everywhere else — and P3 is the lane that would find out in production.
const swResult = await new Promise((resolve, reject) => {
  const bootstrap = `
    const { parentPort, workerData } = require('node:worker_threads');
    (async () => {
      try {
        const { ctx, pairingId, sessionKeyHex, A, kekHexInputs } = workerData;
        globalThis.self = globalThis;
        delete globalThis.process;
        delete globalThis.Buffer;
        delete globalThis.require;
        globalThis.window = undefined;
        globalThis.document = undefined;
        const m = await import(workerData.url);
        const context = m.fromHex(ctx);
        const keys = await m.trafficKeys({
          pairingId, sessionKey: m.fromHex(sessionKeyHex), context, role: 'phone',
        });
        const sender = { ...keys.send, sessionPrefix: m.fromHex(A.sessionPrefixHex) };
        const ct = await m.seal({
          sender, frameType: A.frameType, kid: A.kid, seq: A.seq, pairEpoch: A.pairEpoch,
          plaintext: new TextEncoder().encode(A.plaintextUtf8),
        });
        const keksOut = [];
        for (const r of kekHexInputs) {
          keksOut.push([r.kind, m.toHex(await m.kek({
            pairingId, sharedSecret: m.fromHex(r.sharedSecretHex), context, recipientKey: r.publicKeySec1Hex,
          }))]);
        }
        let capThrew = false;
        try { m.pairContext({ userId: 'a'.repeat(256), phoneDeviceId: 'b', peerDeviceId: 'c', pairEpoch: 1 }); }
        catch { capThrew = true; }
        parentPort.postMessage({
          ok: true,
          p2c: m.toHex(keys.send.rawBytes),
          c2p: m.toHex(keys.recv.rawBytes),
          ct: m.toHex(ct),
          keks: keksOut,
          capThrew,
        });
      } catch (e) {
        parentPort.postMessage({ ok: false, error: String(e && e.message || e) });
      }
    })();
  `;
  const w = new Worker(bootstrap, {
    eval: true,
    workerData: {
      url: pathToFileURL(KDF_MODULE).href,
      ctx: V.contextBytesHex,
      pairingId: CTX_INPUT.pairingId,
      sessionKeyHex: V.traffic.sessionKeyHex,
      A,
      kekHexInputs: V.kek.recipients.map((r) => ({
        kind: r.kind, publicKeySec1Hex: r.publicKeySec1Hex, sharedSecretHex: V.kek.sharedSecretHex,
      })),
    },
  });
  w.once('message', (m) => { resolve(m); w.terminate(); });
  w.once('error', reject);
});

check('SW context: the module runs with no process/Buffer/require/DOM', swResult.ok, swResult.error);
if (swResult.ok) {
  eq('SW context: k_p2c', swResult.p2c, V.traffic.phoneToComputerKeyHex);
  eq('SW context: k_c2p', swResult.c2p, V.traffic.computerToPhoneKeyHex);
  eq('SW context: vector A ciphertext', swResult.ct, A.ciphertextHex);
  for (const [kind, hex] of swResult.keks) {
    eq(`SW context: ${kind} kek`, hex, V.kek.recipients.find((r) => r.kind === kind).kekHex);
  }
  check('SW context: the u8 cap still throws', swResult.capThrew);
}

// ── result ─────────────────────────────────────────────────────────────────
const total = passed + failed;
console.log(`kdf-vectors: ${passed}/${total} checks passed`);
process.exit(failed === 0 ? 0 : 1);
