#!/usr/bin/env node
/**
 * tests/sas-vectors.test.mjs — the SAS transcript is frozen, and stays frozen.
 *
 * Three implementations must produce identical digits from identical inputs:
 * the web page, the extension service worker, and the Android app. When they
 * disagree, every mode-ON pairing fails and the tempting "fix" is to weaken the
 * input until the digits agree — at which point the verification code is
 * decoration. tests/sas-vectors.json is the contract that makes that visible.
 * Kotlin asserts the same file in P4 (instrumented SasVectorsTest).
 *
 * A fixture generated by the implementation it tests proves only that the code
 * is deterministic. So this file adds three independent things:
 *
 *   1. An INDEPENDENT HKDF. The vectors are computed through WebCrypto
 *      (`crypto.subtle.deriveBits`); the cross-check recomputes them through
 *      `node:crypto.hkdfSync`, a different implementation of RFC 5869. If the
 *      frozen layout were being hashed wrongly but consistently, these two
 *      would still have to agree with each other — and they are the two code
 *      paths the web and Android sides actually use.
 *
 *   2. The TRANSCRIPT, not just the digits. Five digits collide one time in
 *      100000, so a transcript bug that happened to collide would read as a
 *      pass. Each vector pins its exact IKM bytes.
 *
 *   3. A DISCRIMINATING pair. v3 and v4 differ in exactly one byte-range — the
 *      service worker's static key — and must produce different digits. That is
 *      the B9 attack: under the old two-key layout a swapped SW key was
 *      invisible to the user, because the SW has no UI to show a code on, while
 *      being the one leg that decrypts notification bodies with the panel shut.
 *      An assertion that only checked "v3 still hashes to 50690" would pass
 *      just as happily with the SW key left out of the transcript entirely.
 *
 * Plus a service-worker-context run: the same module, executed in a worker with
 * `process`, `Buffer`, `require`, `window` and `document` removed and `self`
 * bound to the global — the constraint set an MV3 service worker imposes.
 */

import { readFileSync } from 'node:fs';
import { hkdfSync } from 'node:crypto';
import { Worker } from 'node:worker_threads';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import { sasDigits, sasTranscript, toHex, fromHex, compareBytes, canonicalKeySet } from '../lib/e2e/sas.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SAS_MODULE = join(ROOT, 'lib', 'e2e', 'sas.mjs');

const VECTORS = JSON.parse(readFileSync(join(HERE, 'sas-vectors.json'), 'utf8'));

let passed = 0;
let failed = 0;
function check(name, ok, detail = '') {
  if (ok) { passed++; return; }
  failed++;
  console.error(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
}
function eq(name, actual, expected) {
  check(name, actual === expected, `expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
}

// ── 1. every vector reproduces, transcript first, then digits ───────────────
for (const v of VECTORS.vectors) {
  const input = { pairingId: v.pairingId, epk: v.epk, keys: v.keys, pairEpoch: v.pairEpoch, modeOn: v.modeOn };
  eq(`${v.id}: transcript`, toHex(sasTranscript(input)), v.transcriptHex);
  eq(`${v.id}: digits (WebCrypto)`, await sasDigits(input), v.digits);
  check(`${v.id}: digits are 5 ASCII digits`, /^[0-9]{5}$/.test(v.digits), v.digits);
}

// ── 2. independent HKDF over the frozen transcript ──────────────────────────
// node:crypto.hkdfSync is a different RFC 5869 implementation from
// crypto.subtle.deriveBits. Agreement between them is the real cross-check.
for (const v of VECTORS.vectors) {
  const okm = Buffer.from(hkdfSync(
    'sha256',
    Buffer.from(v.transcriptHex, 'hex'),        // ikm
    Buffer.from(v.pairingId, 'utf8'),           // salt
    Buffer.from(VECTORS.info, 'utf8'),          // info
    4,                                          // the first 4 bytes of the OKM
  ));
  eq(`${v.id}: digits (node:crypto, independent)`,
    String(okm.readUInt32BE(0) % 100000).padStart(5, '0'), v.digits);
}

// ── 3. the vectors DISCRIMINATE (an absence-only proof would be vacuous) ────
const byId = Object.fromEntries(VECTORS.vectors.map((v) => [v.id, v]));
check('B9: swapping ONLY the SW key changes the digits',
  byId['v3-3key-mode-on'].digits !== byId['v4-3key-sw-swapped'].digits,
  `both are ${byId['v3-3key-mode-on'].digits}`);
check('B9: v3 and v4 differ in exactly one key',
  byId['v3-3key-mode-on'].keys.filter((k) => !byId['v4-3key-sw-swapped'].keys.includes(k)).length === 1);
check('modeByte alone changes the digits',
  byId['v1-2key-mode-off'].digits !== byId['v2-2key-mode-on'].digits,
  `both are ${byId['v1-2key-mode-off'].digits}`);
check('v1 and v2 differ ONLY in modeOn',
  byId['v1-2key-mode-off'].pairingId === byId['v2-2key-mode-on'].pairingId &&
  byId['v1-2key-mode-off'].epk === byId['v2-2key-mode-on'].epk &&
  byId['v1-2key-mode-off'].pairEpoch === byId['v2-2key-mode-on'].pairEpoch);
check('the frozen set covers the 2-, 3- and 4-key cases',
  [2, 3, 4].every((n) => VECTORS.vectors.some((v) => v.keys.length === n)));

// ── 4. the key list is a canonical SET, not an ordered list ─────────────────
{
  const v = byId['v3-3key-mode-on'];
  const base = { pairingId: v.pairingId, epk: v.epk, pairEpoch: v.pairEpoch, modeOn: v.modeOn };
  const reversed = [...v.keys].reverse();
  eq('key order does not change the digits', await sasDigits({ ...base, keys: reversed }), v.digits);
  eq('a duplicate key is collapsed', await sasDigits({ ...base, keys: [...v.keys, v.keys[1]] }), v.digits);
  check('canonicalKeySet sorts by unsigned byte order',
    canonicalKeySet(reversed).every((k, i, arr) => i === 0 || compareBytes(arr[i - 1], k) < 0));
  // 0x80 is negative as a signed byte. A signed comparator would order these
  // the other way round, and the three implementations would disagree on
  // exactly the keys that look most like real ones.
  check('sorting is UNSIGNED (0x80 sorts after 0x7f)',
    compareBytes(fromHex('80'), fromHex('7f')) > 0);
}

// ── 5. length framing actually disambiguates ────────────────────────────────
// Without the u8 length prefixes, ["aabb","cc"] and ["aa","bbcc"] would flatten
// to the same bytes. This is the concatenation ambiguity the framing exists for.
{
  const base = { pairingId: 'amb', epk: 'aa', pairEpoch: 7, modeOn: true };
  const a = toHex(sasTranscript({ ...base, keys: ['aabb', 'cc'] }));
  const b = toHex(sasTranscript({ ...base, keys: ['aa', 'bbcc'] }));
  check('u8 length framing disambiguates concatenation', a !== b, `both are ${a}`);
}

// ── 6. malformed input fails loudly rather than hashing something ───────────
for (const [name, input] of [
  ['empty key set', { pairingId: 'x', epk: 'aa', keys: [], pairEpoch: 1, modeOn: false }],
  ['empty pairingId', { pairingId: '', epk: 'aa', keys: ['bb'], pairEpoch: 1, modeOn: false }],
  ['negative pairEpoch', { pairingId: 'x', epk: 'aa', keys: ['bb'], pairEpoch: -1, modeOn: false }],
  ['odd-length hex key', { pairingId: 'x', epk: 'aa', keys: ['abc'], pairEpoch: 1, modeOn: false }],
]) {
  let threw = false;
  try { await sasDigits(input); } catch { threw = true; }
  check(`rejects ${name}`, threw);
}

// ── 7. the module is service-worker clean, statically ───────────────────────
{
  // Comments are stripped FIRST. The module's own header explains that it must
  // not touch `window` or `document` — a grep over the raw source matches that
  // prose and fails a module that is in fact clean. A rule that its own
  // documentation can violate is not checking the code.
  const src = readFileSync(SAS_MODULE, 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
  check('sas.mjs imports no Node built-in', !/from\s+['"]node:/.test(src));
  check('sas.mjs touches no DOM global', !/\b(window|document|localStorage)\b/.test(src));
  check('the comment-stripper did not empty the file', /export function sasTranscript/.test(src));
}

// ── 8. …and dynamically: the same vectors, under SW constraints ─────────────
// `process`, `Buffer` and `require` are removed and `self` is bound to the
// global before the module is imported, which is the shape an MV3 service
// worker presents. A module that reached for any of them would throw here and
// pass everywhere else — that divergence is the whole risk B9 is about.
const swResult = await new Promise((resolve, reject) => {
  const bootstrap = `
    const { parentPort, workerData } = require('node:worker_threads');
    (async () => {
      try {
        const vectors = workerData.vectors;
        const url = workerData.url;
        globalThis.self = globalThis;
        delete globalThis.process;
        delete globalThis.Buffer;
        delete globalThis.require;
        globalThis.window = undefined;
        globalThis.document = undefined;
        const { sasDigits } = await import(url);
        const out = [];
        for (const v of vectors) {
          out.push([v.id, await sasDigits({
            pairingId: v.pairingId, epk: v.epk, keys: v.keys,
            pairEpoch: v.pairEpoch, modeOn: v.modeOn,
          })]);
        }
        parentPort.postMessage({ ok: true, out });
      } catch (e) {
        parentPort.postMessage({ ok: false, error: String(e && e.message || e) });
      }
    })();
  `;
  const w = new Worker(bootstrap, {
    eval: true,
    workerData: { vectors: VECTORS.vectors, url: pathToFileURL(SAS_MODULE).href },
  });
  w.once('message', (m) => { resolve(m); w.terminate(); });
  w.once('error', reject);
});

check('SW context: the module runs with no process/Buffer/require/DOM',
  swResult.ok, swResult.error);
if (swResult.ok) {
  const got = Object.fromEntries(swResult.out);
  for (const v of VECTORS.vectors) {
    eq(`${v.id}: digits (service-worker context)`, got[v.id], v.digits);
  }
}

// ── result ─────────────────────────────────────────────────────────────────
const total = passed + failed;
console.log(`sas-vectors: ${passed}/${total} checks passed`);
process.exit(failed === 0 ? 0 : 1);
