package com.dnkdialer.companion

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent

/**
 * Receives Accept / Decline broadcasts from the connection-request
 * notification's action buttons. The actual decision logic lives in
 * [PhoneService] — this receiver is a thin pass-through whose only job
 * is to route the user's tap back to the running service.
 *
 * Registered programmatically in PhoneService.onCreate with
 * RECEIVER_NOT_EXPORTED on API 33+ so no other process can spoof an
 * Accept and trick us into completing a connection the user didn't
 * approve. The PendingIntents that fire these broadcasts are also
 * FLAG_IMMUTABLE so they cannot be mutated by an attacker mid-flight.
 *
 * Action payload is just the request id (a UUID generated by PhoneServer
 * when the WS upgrade arrived). PhoneService looks the id up against
 * its pending map and calls acceptPendingConnection / declinePendingConnection.
 *
 * NOTE: this receiver is intentionally NOT declared in AndroidManifest.xml
 * — registering at runtime against the foreground PhoneService instance
 * gives us a clean lifecycle (no broadcasts get queued after the
 * service is destroyed) and an easy way to share state with the service
 * via a SHARED_BROADCAST_TARGET reference rather than re-binding.
 */
class ConnectionRequestReceiver : BroadcastReceiver() {

    companion object {
        const val ACTION_ACCEPT_CONNECTION =
            "com.dnkdialer.companion.ACTION_ACCEPT_CONNECTION"
        const val ACTION_DECLINE_CONNECTION =
            "com.dnkdialer.companion.ACTION_DECLINE_CONNECTION"
        const val EXTRA_REQUEST_ID = "request_id"

        /**
         * The currently-bound service handles broadcasts directly so we
         * can route decisions without re-binding. Set/cleared by
         * PhoneService.onCreate / onDestroy. Nullable: an in-flight
         * broadcast that arrives after the service is killed is a no-op.
         */
        @Volatile
        var serviceHandler: ((String, Boolean) -> Unit)? = null
    }

    override fun onReceive(context: Context, intent: Intent) {
        val requestId = intent.getStringExtra(EXTRA_REQUEST_ID) ?: return
        val accept = when (intent.action) {
            ACTION_ACCEPT_CONNECTION -> true
            ACTION_DECLINE_CONNECTION -> false
            else -> return
        }
        android.util.Log.d(
            "ConnectionRequestReceiver",
            "Received ${intent.action} for requestId=$requestId"
        )
        serviceHandler?.invoke(requestId, accept)
    }
}
