package com.dnkdialer.companion

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Log
import androidx.core.content.edit
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.SecureRandom
import java.security.spec.ECGenParameterSpec
import java.security.spec.PKCS8EncodedKeySpec
import javax.crypto.Cipher
import javax.crypto.KeyAgreement
import javax.crypto.KeyGenerator
import javax.crypto.spec.GCMParameterSpec

/**
 * E2E programme, phase P4 Part 2 (a2) — P-256 ECDH, on both of the two very
 * different platforms this one app runs on.
 *
 * ## The API-level split, and why there are two code paths at all
 *
 * The Gate 1 ruling (R1) is P-256 everywhere, AndroidKeyStore ECDH on API 31+,
 * and a software fallback on API 26–30 using Conscrypt/Tink only. That split is
 * forced by the platform, not chosen:
 *
 *  - `KeyProperties.PURPOSE_AGREE_KEY` — the only purpose a Keystore key can
 *    carry that permits ECDH — **is API 31+**. This app's minSdk is 26. On API
 *    26–30 there is no hardware-backed key agreement available at any price;
 *    a Keystore EC key there can sign and nothing else. This was measured, not
 *    read: it is the Gate 1 input recorded in the P4 (s3) checkpoint line.
 *  - A Keystore key's purposes are immutable after generation, so the two paths
 *    cannot share one key object. They share the *curve*, the *encoding*, and
 *    the *key schedule*, which is what actually has to match the browser.
 *
 * ### API 31+ — [Backend.ANDROID_KEYSTORE]
 * The private key never leaves the TEE (or StrongBox). `KeyAgreement` is
 * obtained from the `AndroidKeyStore` provider, which is mandatory: the default
 * provider cannot use a Keystore key handle and fails with an opaque
 * `InvalidKeyException` that reads like a corrupt key.
 *
 * ### API 26–30 — [Backend.SOFTWARE_WRAPPED]
 * The EC keypair is generated by the platform's own provider (Conscrypt /
 * AndroidOpenSSL — there is deliberately **no hand-rolled EC arithmetic
 * anywhere in this app**, per the ruling), and then it must be kept somewhere.
 * The requirement is that it be non-exportable, so:
 *
 *  - The PKCS#8 private key is sealed with **AES-256-GCM under a separate
 *    AndroidKeyStore AES key** (`PURPOSE_ENCRYPT | PURPOSE_DECRYPT`, available
 *    since API 23). The wrapping key itself is hardware-backed and cannot be
 *    read out, so a rooted-at-rest attacker who copies the prefs file gets
 *    ciphertext and nothing else.
 *  - The plaintext PKCS#8 bytes exist only inside one method, and are
 *    **zeroed in a `finally`** before it returns — including on the throw path,
 *    which is the path that actually gets forgotten.
 *  - There is no API that returns the private key, encoded or otherwise.
 *    [E2eKeyAgreement] exposes agreement results, never key material.
 *
 * This is weaker than a TEE key and is documented as such rather than papered
 * over: on API 26–30 the key is protected by the Keystore's AES key, which is
 * the strongest thing those releases offer for this purpose.
 *
 * ## What is NOT here
 *
 * Sealing (AES-GCM of frame bodies), the envelope and the dedupe window are
 * P4 (c). The SAS is P4 (b). This file's whole job is: produce a valid shared
 * secret, or refuse loudly.
 */
object E2eKeyAgreement {

    private const val TAG = "E2eKeyAgreement"

    private const val ANDROID_KEYSTORE = "AndroidKeyStore"

    private const val ECDH = "ECDH"

    private const val CURVE = "secp256r1"

    /** A raw P-256 ECDH result is the shared point's X coordinate: 32 bytes. */
    const val SHARED_SECRET_BYTES = 32

    /** API level at which `PURPOSE_AGREE_KEY` — and therefore Keystore ECDH — exists. */
    const val API_KEYSTORE_ECDH = Build.VERSION_CODES.S // 31

    /** Which of the two paths this device is on. */
    enum class Backend {
        /** API 31+. Private key confined to TEE / StrongBox. */
        ANDROID_KEYSTORE,

        /** API 26–30. Software key, sealed at rest under a Keystore AES key. */
        SOFTWARE_WRAPPED,
    }

    /** Thrown when agreement cannot be performed or its result is unusable. */
    class AgreementException(message: String, cause: Throwable? = null) :
        RuntimeException(message, cause)

    /** The path this device will take. A pure platform fact; generates nothing. */
    @JvmStatic
    fun backend(): Backend =
        if (Build.VERSION.SDK_INT >= API_KEYSTORE_ECDH) {
            Backend.ANDROID_KEYSTORE
        } else {
            Backend.SOFTWARE_WRAPPED
        }

    // ------------------------------------------------------- ephemeral side

    /**
     * The ephemeral keypair the ACCEPTING device mints, whose public half is the
     * `epk` in the frozen SAS transcript (§13.3).
     *
     * Deliberately software-only on every API level: an ephemeral lives for one
     * Accept, is never persisted, and putting it in the Keystore would buy
     * nothing while making [close] unable to actually destroy it.
     *
     * Use it in a `try`/`finally` and call [close]. Kotlin's [AutoCloseable] is
     * implemented so `use { }` works.
     */
    class Ephemeral internal constructor(
        /** The 65-byte uncompressed SEC1 public key that goes on the wire. */
        val publicSec1: ByteArray,
        private var priv: PrivateKey?,
    ) : AutoCloseable {

        /**
         * ECDH against one recipient's static public key.
         * @throws E2eKeyEncoding.InvalidPublicKeyException the peer point is not
         *         a valid P-256 point (invalid-curve attack, corrupt key).
         * @throws AgreementException the result is unusable.
         */
        fun agreeWith(peerSec1: ByteArray): ByteArray {
            val p = priv ?: throw AgreementException("ephemeral key already closed")
            return agree(p, peerSec1, null)
        }

        override fun close() {
            priv = null
        }
    }

    /**
     * Mint a fresh ephemeral P-256 keypair. One per Accept — reusing one across
     * Accepts would defeat the `pairEpoch` rekey in §13.8.
     */
    @JvmStatic
    fun mintEphemeral(): Ephemeral {
        val gen = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC)
        gen.initialize(ECGenParameterSpec(CURVE), SecureRandom())
        val kp = gen.generateKeyPair()
        return Ephemeral(E2eKeyEncoding.toSec1(kp.public), kp.private)
    }

    // ---------------------------------------------------- static device side

    /**
     * This device's long-lived public key, in the frozen wire encoding
     * (uncompressed SEC1, 65 bytes). Generates the key on first use.
     *
     * Note this is NOT [E2eKeyStore.publicKeyBytes], which returns X.509 SPKI —
     * see the [E2eKeyEncoding] class doc for why those two must never be
     * confused.
     */
    @JvmStatic
    fun devicePublicSec1(ctx: Context): ByteArray = when (backend()) {
        Backend.ANDROID_KEYSTORE ->
            E2eKeyEncoding.toSec1(keystorePublicKey(ctx))
        Backend.SOFTWARE_WRAPPED ->
            SoftwareDeviceKey.publicSec1(ctx)
    }

    /**
     * ECDH between this device's STATIC key and a peer point — the recipient
     * side of the handshake, where the phone opens a wrap addressed to it.
     */
    @JvmStatic
    fun agreeWithDeviceKey(ctx: Context, peerSec1: ByteArray): ByteArray =
        when (backend()) {
            Backend.ANDROID_KEYSTORE ->
                agree(keystorePrivateKey(ctx), peerSec1, ANDROID_KEYSTORE)
            Backend.SOFTWARE_WRAPPED ->
                SoftwareDeviceKey.agree(ctx, peerSec1)
        }

    /** Delete this device's static key on both paths. Reset / sign-out (§13.8). */
    @JvmStatic
    fun rotateDeviceKey(ctx: Context) {
        when (backend()) {
            Backend.ANDROID_KEYSTORE -> E2eKeyStore.rotate(ctx)
            Backend.SOFTWARE_WRAPPED -> SoftwareDeviceKey.rotate(ctx)
        }
    }

    // ------------------------------------------ forced-path test entry points

    /*
     * The API 26–30 fallback is the path that will run on the OLDEST devices and
     * get the LEAST testing, because CI and the dev box both run a modern
     * emulator where [backend] never selects it. These three entry points let
     * the instrumented suite drive the software path explicitly on ANY API
     * level, so the wrapped-key store, the zeroing and the ECDH itself are
     * proven on every run rather than only when an API 26 image happens to be
     * installed. They are a supplement to, not a substitute for, a real API 26
     * emulator run — a forced run on API 36 cannot show that
     * `PURPOSE_AGREE_KEY` is absent below 31, which is the whole reason the
     * fallback exists.
     */

    /** Drive the API 26–30 path's public key on any API level. Tests only. */
    @androidx.annotation.VisibleForTesting
    @JvmStatic
    fun softwarePathPublicSec1(ctx: Context): ByteArray = SoftwareDeviceKey.publicSec1(ctx)

    /** Drive the API 26–30 path's ECDH on any API level. Tests only. */
    @androidx.annotation.VisibleForTesting
    @JvmStatic
    fun softwarePathAgree(ctx: Context, peerSec1: ByteArray): ByteArray =
        SoftwareDeviceKey.agree(ctx, peerSec1)

    /** Drive the API 26–30 path's rotation on any API level. Tests only. */
    @androidx.annotation.VisibleForTesting
    @JvmStatic
    fun softwarePathRotate(ctx: Context) = SoftwareDeviceKey.rotate(ctx)

    // ------------------------------------------------------------- the ECDH

    /**
     * The single place ECDH happens. Everything funnels here so the peer-point
     * validation and the all-zero check cannot be bypassed by a new call site.
     *
     * `provider` is `AndroidKeyStore` for a Keystore private key and null (the
     * platform default, i.e. Conscrypt) otherwise. Passing the wrong one is the
     * classic "InvalidKeyException on a perfectly good key".
     */
    private fun agree(priv: PrivateKey, peerSec1: ByteArray, provider: String?): ByteArray {
        // Validate BEFORE the key ever reaches KeyAgreement: an unvalidated peer
        // point handed to ECDH is the invalid-curve attack, and neither Conscrypt
        // nor the Keystore reliably rejects it for us.
        val peer = E2eKeyEncoding.fromSec1(peerSec1)
        val z = try {
            val ka = if (provider != null) {
                KeyAgreement.getInstance(ECDH, provider)
            } else {
                KeyAgreement.getInstance(ECDH)
            }
            ka.init(priv)
            ka.doPhase(peer, true)
            ka.generateSecret()
        } catch (e: java.security.GeneralSecurityException) {
            throw AgreementException("P-256 ECDH failed (${backend()})", e)
        }
        if (z.size != SHARED_SECRET_BYTES) {
            z.fill(0)
            throw AgreementException(
                "ECDH returned ${z.size} bytes; P-256 must return $SHARED_SECRET_BYTES"
            )
        }
        // Refuse an all-zero secret rather than deriving a key from it (Gate 1).
        try {
            E2eKdf.requireNonZeroSharedSecret(z)
        } catch (e: E2eKdf.KdfException) {
            z.fill(0)
            throw AgreementException(e.message ?: "all-zero shared secret", e)
        }
        return z
    }

    private fun keystorePublicKey(ctx: Context): java.security.PublicKey {
        E2eKeyStore.publicKeyBytes(ctx) // generate-on-first-use
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        val alias = E2eKeyStore.aliasFor(E2eKeyStore.Curve.P256)
        return ks.getCertificate(alias)?.publicKey
            ?: throw AgreementException("no certificate for $alias after generation")
    }

    private fun keystorePrivateKey(ctx: Context): PrivateKey {
        E2eKeyStore.publicKeyBytes(ctx) // generate-on-first-use
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        val alias = E2eKeyStore.aliasFor(E2eKeyStore.Curve.P256)
        return ks.getKey(alias, null) as? PrivateKey
            ?: throw AgreementException("no private key for $alias")
    }

    // --------------------------------------------------- API 26–30 fallback

    /**
     * The API 26–30 static device key: generated by Conscrypt, sealed at rest
     * with AES-256-GCM under an AndroidKeyStore wrapping key, and never exposed.
     *
     * Kept as an internal object rather than folded into [E2eKeyStore] so that
     * the "no Keystore ECDH below 31" boundary is one readable unit, and so the
     * dangerous method — [agree], the only one that ever materialises a private
     * key — is short enough to audit at a glance.
     */
    internal object SoftwareDeviceKey {

        private const val PREFS = "computercaller_e2e_swkey"

        /** Versioned like the Keystore alias (RESUME-PROTOCOL rule 6). */
        private const val RECORD_VERSION = 1
        private const val KEY_VERSION = "v"
        private const val KEY_WRAPPED_PRIV = "priv_wrapped_b64"
        private const val KEY_IV = "priv_iv_b64"
        private const val KEY_PUBLIC = "pub_sec1_b64"

        /** Alias of the AES key that wraps the EC private key. Never the EC key itself. */
        private const val WRAP_ALIAS = "cc-e2e-swwrap-v1"

        private const val GCM_IV_BYTES = 12
        private const val GCM_TAG_BITS = 128

        private fun prefs(ctx: Context) =
            ctx.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        fun publicSec1(ctx: Context): ByteArray {
            ensure(ctx)
            val b64 = prefs(ctx).getString(KEY_PUBLIC, null)
                ?: throw AgreementException("software device key has no stored public half")
            return E2eKeyEncoding.fromBase64Url(b64)
        }

        fun rotate(ctx: Context) {
            prefs(ctx).edit { clear() }
            try {
                KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }.deleteEntry(WRAP_ALIAS)
            } catch (e: java.security.GeneralSecurityException) {
                Log.w(TAG, "rotate(): could not delete the wrapping key", e)
            } catch (e: java.io.IOException) {
                Log.w(TAG, "rotate(): could not open the Keystore", e)
            }
            ensure(ctx)
        }

        /**
         * The ONLY method that materialises the private key. The PKCS#8 bytes
         * live in `pkcs8` and are zeroed in the `finally` — on the throw path
         * too, which is the path that gets forgotten.
         */
        fun agree(ctx: Context, peerSec1: ByteArray): ByteArray {
            ensure(ctx)
            val p = prefs(ctx)
            val wrapped = E2eKeyEncoding.fromBase64Url(
                p.getString(KEY_WRAPPED_PRIV, null)
                    ?: throw AgreementException("software device key is missing")
            )
            val iv = E2eKeyEncoding.fromBase64Url(
                p.getString(KEY_IV, null)
                    ?: throw AgreementException("software device key has no IV")
            )
            var pkcs8: ByteArray? = null
            try {
                pkcs8 = unseal(wrapped, iv)
                val priv = java.security.KeyFactory.getInstance(KeyProperties.KEY_ALGORITHM_EC)
                    .generatePrivate(PKCS8EncodedKeySpec(pkcs8))
                return E2eKeyAgreement.agree(priv, peerSec1, null)
            } catch (e: java.security.GeneralSecurityException) {
                throw AgreementException("software-key ECDH failed", e)
            } finally {
                pkcs8?.fill(0)
            }
        }

        private fun ensure(ctx: Context) {
            val p = prefs(ctx)
            val storedVersion = p.getInt(KEY_VERSION, 0)
            if (storedVersion != 0 && storedVersion != RECORD_VERSION) {
                throw AgreementException(
                    "software E2E key record is v$storedVersion but this build understands " +
                        "only v$RECORD_VERSION — refusing to use it; a migration is required"
                )
            }
            if (storedVersion == RECORD_VERSION && p.contains(KEY_WRAPPED_PRIV)) return

            val gen = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC)
            gen.initialize(ECGenParameterSpec(CURVE), SecureRandom())
            val kp = gen.generateKeyPair()
            val pkcs8 = kp.private.encoded
                ?: throw AgreementException("provider refused to encode the software private key")
            try {
                val (ct, iv) = seal(pkcs8)
                p.edit {
                    putInt(KEY_VERSION, RECORD_VERSION)
                    putString(KEY_WRAPPED_PRIV, E2eKeyEncoding.toBase64Url(ct))
                    putString(KEY_IV, E2eKeyEncoding.toBase64Url(iv))
                    putString(KEY_PUBLIC, E2eKeyEncoding.toBase64Url(E2eKeyEncoding.toSec1(kp.public)))
                }
            } finally {
                pkcs8.fill(0)
            }
            if (BuildConfig.DEBUG) Log.d(TAG, "software device key generated and sealed")
        }

        /** AES-256-GCM under the hardware-backed wrapping key. */
        private fun seal(plain: ByteArray): Pair<ByteArray, ByteArray> {
            val c = Cipher.getInstance("AES/GCM/NoPadding")
            c.init(Cipher.ENCRYPT_MODE, wrappingKey())
            return c.doFinal(plain) to c.iv
        }

        private fun unseal(ct: ByteArray, iv: ByteArray): ByteArray {
            if (iv.size != GCM_IV_BYTES) {
                throw AgreementException("stored IV is ${iv.size} bytes, expected $GCM_IV_BYTES")
            }
            val c = Cipher.getInstance("AES/GCM/NoPadding")
            c.init(Cipher.DECRYPT_MODE, wrappingKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
            return c.doFinal(ct)
        }

        /**
         * The AES wrapping key, generated on first use inside AndroidKeyStore.
         * `setRandomizedEncryptionRequired` is left at its default (true), so the
         * platform supplies the IV and a nonce-reuse bug is not expressible here.
         */
        private fun wrappingKey(): javax.crypto.SecretKey {
            val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
            (ks.getKey(WRAP_ALIAS, null) as? javax.crypto.SecretKey)?.let { return it }
            val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            gen.init(
                KeyGenParameterSpec.Builder(
                    WRAP_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    // The phone relays with the screen locked and nobody present.
                    .setUserAuthenticationRequired(false)
                    .build()
            )
            return gen.generateKey()
        }
    }
}

/**
 * The per-Accept session key (SK of §13.8), and the one place it is minted.
 *
 * Separate from [E2eKdf] because minting needs a CSPRNG and the KDF must stay a
 * pure function — a pure KDF is testable against fixed vectors, and a KDF that
 * quietly reaches for randomness is not.
 */
object E2eSessionKey {

    /** A fresh session key. Called once per Accept; the epoch bumps with it. */
    @JvmStatic
    fun mint(): ByteArray = ByteArray(E2eKdf.KEY_BYTES).also { SecureRandom().nextBytes(it) }
}
